#######################################################################################################################
# Configuration intended to be mounted as `application-local.yaml` for the vacman-backend Spring Boot application.
#
# This file provides environment-specific overrides to the default configuration.
#######################################################################################################################

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect

management:
  otlp:
    metrics:
      export:
        url: https://dynatrace.dev-dp.admin.dts-stn.com/e/21a07aef-852b-4d9b-aa87-ee5f8b79f8c9/api/v2/otlp/v1/metrics
  
application:
  security:
    # Disables custom application security.
    # Make sure this is never set to true in production.
    disabled: true