export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ErrorCodes = {
  UNCAUGHT_ERROR: 'UNC-0000',

  // auth error codes
  MISCONFIGURED_PROVIDER: 'AUTH-0001',
  ACCESS_FORBIDDEN: 'AUTH-0002',
  MISSING_AUTH_HEADER: 'AUTH-0003',
  DISCOVERY_ENDPOINT_MISSING: 'AUTH-0004',
  MISSING_ID_TOKEN: 'AUTH-0005',

  // component error codes
  MISSING_LANG_PARAM: 'CMP-0001',

  // i18n error codes
  NO_LANGUAGE_FOUND: 'I18N-0001',
  MISSING_TRANSLATION_KEY: 'I18N-0002',

  // instance error codes
  NO_FACTORY_PROVIDED: 'INST-0001',

  // route error codes
  ROUTE_NOT_FOUND: 'RTE-0001',

  // dev-only error codes
  TEST_ERROR_CODE: 'DEV-0001',

  // form error codes
  MISSING_TAB_ID: 'FRM-0000',
  UNRECOGNIZED_ACTION: 'FRM-0001',

  // service error codes
  NO_PROVINCE_FOUND: 'SVC-0001',
  NO_BRANCH_FOUND: 'SVC-0002',
  NO_CLASSIFICATION_FOUND: 'SVC-0003',
  NO_EMPLOYMENT_OPPORTUNITY_TYPE_FOUND: 'SVC-0004',
  NO_EDUCATION_LEVEL_FOUND: 'SVC-0005',
  NO_LANGUAGE_REFERRAL_TYPE_FOUND: 'SVC-0006',
  NO_CITY_FOUND: 'SVC-007',
  NO_WFA_STATUS_FOUND: 'SVC-0008',
  NO_LANGUAGE_OF_CORRESPONDENCE_FOUND: 'SVC-0009',
  NO_DIRECTORATE_FOUND: 'SVC-0010',

  // vacman api error codes
  VACMAN_API_ERROR: 'API-0001',
} as const;
