apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacman-frontend
  labels:
    app.kubernetes.io/name: vacman-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vacman-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vacman-frontend
    spec:
      containers:
        - name: vacman-frontend
          # Note: image tag should be pinned to a specific version in overlays
          image: dtsrhpdevscedacr.azurecr.io/vacman/vacman-frontend
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
