--liquibase formatted sql

--changeset system:h2-modify 
ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL; 

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;
 
ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD CONSTRAINT APPNTMNTNONADVRTSD_PK PRIMARY KEY (ID);

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD CONSTRAINT APPNTMNTNONADVRTSD_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_CITY ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_CITY ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_CITY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();  
 
ALTER TABLE CD_CITY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_CITY ADD CONSTRAINT CITY_PK PRIMARY KEY (ID);

ALTER TABLE CD_CITY ADD CONSTRAINT CITY_UK UNIQUE (CODE, PROVINCE_TERRITORY_ID, EXPIRY_DATE);


ALTER TABLE CD_CLASSIFICATION ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_CLASSIFICATION ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_CLASSIFICATION ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_CLASSIFICATION ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_CLASSIFICATION ADD CONSTRAINT CLSFCTN_PK PRIMARY KEY (ID);

ALTER TABLE CD_CLASSIFICATION ADD CONSTRAINT CLSFCTN_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_EMPLOYMENT_EQUITY ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE(); 

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD CONSTRAINT EMPLYMNTEQT_PK PRIMARY KEY (ID);

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD CONSTRAINT EMPLYMNTEQT_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE; 

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT EMPOPPR_PK PRIMARY KEY (ID);

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT EMPOPPR_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_EMPLOYMENT_TENURE ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_EMPLOYMENT_TENURE ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_EMPLOYMENT_TENURE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_EMPLOYMENT_TENURE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_EMPLOYMENT_TENURE ADD CONSTRAINT EMPTNR_PK PRIMARY KEY (ID);

ALTER TABLE CD_EMPLOYMENT_TENURE ADD CONSTRAINT EMPTNR_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_LANGUAGE ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_LANGUAGE ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_LANGUAGE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_LANGUAGE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_LANGUAGE ADD CONSTRAINT LNG_PK PRIMARY KEY (ID);

ALTER TABLE CD_LANGUAGE ADD CONSTRAINT LNG_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT LNGRFRTYP_PK PRIMARY KEY (ID);

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT LNGRFRTYP_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD CONSTRAINT LNGRQR_PK PRIMARY KEY (ID);

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD CONSTRAINT LNGRQR_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_MATCH_STATUS ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_MATCH_STATUS ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_MATCH_STATUS ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_MATCH_STATUS ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_MATCH_STATUS ADD CONSTRAINT MTCHSTS_PK PRIMARY KEY (ID);

ALTER TABLE CD_MATCH_STATUS ADD CONSTRAINT MTCHSTS_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_PROFILE_STATUS ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_PROFILE_STATUS ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_PROFILE_STATUS ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_PROFILE_STATUS ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_PROFILE_STATUS ADD CONSTRAINT PRFLSTS_PK PRIMARY KEY (ID);

ALTER TABLE CD_PROFILE_STATUS ADD CONSTRAINT PRFLSTS_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_PROVINCE_TERRITORY ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_PROVINCE_TERRITORY ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_PROVINCE_TERRITORY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_PROVINCE_TERRITORY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_PROVINCE_TERRITORY ADD CONSTRAINT PRVNCTRY_PK PRIMARY KEY (ID);

ALTER TABLE CD_PROVINCE_TERRITORY ADD CONSTRAINT PRVNCTRY_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_REQUEST_STATUS ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_REQUEST_STATUS ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_REQUEST_STATUS ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_REQUEST_STATUS ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_REQUEST_STATUS ADD CONSTRAINT RQSTSTS_PK PRIMARY KEY (ID);

ALTER TABLE CD_REQUEST_STATUS ADD CONSTRAINT RQSTSTS_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_SECURITY_CLEARANCE ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_SECURITY_CLEARANCE ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_SECURITY_CLEARANCE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_SECURITY_CLEARANCE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_SECURITY_CLEARANCE ADD CONSTRAINT SCRCLNC_PK PRIMARY KEY (ID);

ALTER TABLE CD_SECURITY_CLEARANCE ADD CONSTRAINT SCRCLNC_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE; 

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD CONSTRAINT SLCTNPRCSSTYP_PK PRIMARY KEY (ID);

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD CONSTRAINT SLCTNPRCSSTYP_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_USER_TYPE ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_USER_TYPE ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_USER_TYPE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_USER_TYPE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_USER_TYPE ADD CONSTRAINT USERTYP_PK PRIMARY KEY (ID);

ALTER TABLE CD_USER_TYPE ADD CONSTRAINT USERTYP_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_WFA_STATUS ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_WFA_STATUS ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_WFA_STATUS ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_WFA_STATUS ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_WFA_STATUS ADD CONSTRAINT WFASTS_PK PRIMARY KEY (ID);

ALTER TABLE CD_WFA_STATUS ADD CONSTRAINT WFASTS_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_WORK_SCHEDULE ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_WORK_SCHEDULE ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_WORK_SCHEDULE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_WORK_SCHEDULE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_WORK_SCHEDULE ADD CONSTRAINT WRKSCHDL_PK PRIMARY KEY (ID);

ALTER TABLE CD_WORK_SCHEDULE ADD CONSTRAINT WRKSCHDL_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE CD_WORK_UNIT ADD EFFECTIVE_DATE TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE CD_WORK_UNIT ADD EXPIRY_DATE TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_WORK_UNIT ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_WORK_UNIT ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CD_WORK_UNIT ADD CONSTRAINT WRKUNT_PK PRIMARY KEY (ID);

ALTER TABLE CD_WORK_UNIT ADD CONSTRAINT WRKUNT_UK UNIQUE (CODE, EXPIRY_DATE);


ALTER TABLE PROFILE_CITY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE_CITY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE; 

ALTER TABLE PROFILE_CITY ADD CONSTRAINT PRFLCTY_PK PRIMARY KEY (ID);

ALTER TABLE PROFILE_CITY ADD CONSTRAINT PRFLCTY_UK UNIQUE (PROFILE_ID, CITY_ID);


ALTER TABLE CLASSIFICATION_PROFILE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE CLASSIFICATION_PROFILE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE CLASSIFICATION_PROFILE ADD CONSTRAINT CLSPRFL_PK PRIMARY KEY (ID);

ALTER TABLE CLASSIFICATION_PROFILE ADD CONSTRAINT CLSPRFL_UK UNIQUE (CLASSIFICATION_ID, PROFILE_ID);


ALTER TABLE EVENT ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE EVENT ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE EVENT ADD CONSTRAINT EVENT_PK PRIMARY KEY (ID);


ALTER TABLE MATCH ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE MATCH ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE MATCH ADD CONSTRAINT MATCH_PK PRIMARY KEY (ID);


ALTER TABLE PROFILE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE PROFILE ADD CONSTRAINT PROFILE_PK PRIMARY KEY (ID);


ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT PEMPOPPR_PK PRIMARY KEY (ID);

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT PEMPOPPR_UK UNIQUE (EMPLOYMENT_OPPORTUNITY_ID, PROFILE_ID);


ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT PLNGRLTYP_PK PRIMARY KEY (ID);

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT PLNGRLTYP_UK UNIQUE (PROFILE_ID, LANGUAGE_REFERRAL_TYPE_ID);


ALTER TABLE REQUEST ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE REQUEST ADD CONSTRAINT REQUEST_PK PRIMARY KEY (ID);


ALTER TABLE REQUEST_CITY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST_CITY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE REQUEST_CITY ADD CONSTRAINT RQSTCTY_PK PRIMARY KEY (ID);

ALTER TABLE REQUEST_CITY ADD CONSTRAINT RQSTCTY_UK UNIQUE (CITY_ID, REQUEST_ID);


ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD CONSTRAINT RQSTEMPLYMNTEQT_PK PRIMARY KEY (ID);

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD CONSTRAINT RQSTEMPLYMNTEQT_UK UNIQUE (EMPLOYMENT_EQUITY_ID, REQUEST_ID);


ALTER TABLE [USER] ADD DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT GETDATE();

ALTER TABLE [USER] ADD DATE_UPDATED TIMESTAMP WITH TIME ZONE;

ALTER TABLE [USER] ADD CONSTRAINT USER_PK PRIMARY KEY (ID);

ALTER TABLE [USER] ADD CONSTRAINT USER_UK UNIQUE (MS_ENTRA_ID);


ALTER TABLE CD_CITY 
    ADD CONSTRAINT CITY_PRVNCTRY_FK FOREIGN KEY 
    ( 
     PROVINCE_TERRITORY_ID
    ) 
    REFERENCES CD_PROVINCE_TERRITORY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE CLASSIFICATION_PROFILE 
    ADD CONSTRAINT CLSPRFL_CLSFCTN_FK FOREIGN KEY 
    ( 
     CLASSIFICATION_ID
    ) 
    REFERENCES CD_CLASSIFICATION 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE CLASSIFICATION_PROFILE 
    ADD CONSTRAINT CLSPRFL_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_CITY 
    ADD CONSTRAINT PRFLCTY_CITY_FK FOREIGN KEY 
    ( 
     CITY_ID
    ) 
    REFERENCES CD_CITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_CITY 
    ADD CONSTRAINT PRFLCTY_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE MATCH 
    ADD CONSTRAINT MATCH_MTCHSTS_FK FOREIGN KEY 
    ( 
     MATCH_STATUS_ID
    ) 
    REFERENCES CD_MATCH_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE MATCH 
    ADD CONSTRAINT MATCH_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE MATCH 
    ADD CONSTRAINT MATCH_REQUEST_FK FOREIGN KEY 
    ( 
     REQUEST_ID
    ) 
    REFERENCES REQUEST 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY 
    ADD CONSTRAINT PEMPTNR_EMPOPPR_FK FOREIGN KEY 
    ( 
     EMPLOYMENT_OPPORTUNITY_ID
    ) 
    REFERENCES CD_EMPLOYMENT_OPPORTUNITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY 
    ADD CONSTRAINT PEMPTNR_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE 
    ADD CONSTRAINT PLNGRLTYP_LNGRFRTYP_FK FOREIGN KEY 
    ( 
     LANGUAGE_REFERRAL_TYPE_ID
    ) 
    REFERENCES CD_LANGUAGE_REFERRAL_TYPE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE 
    ADD CONSTRAINT PLNGRLTYP_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_CDPRSTS_FK FOREIGN KEY 
    ( 
     PROFILE_STATUS_ID
    ) 
    REFERENCES CD_PROFILE_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_CITY_FK FOREIGN KEY 
    ( 
     CITY_ID
    ) 
    REFERENCES CD_CITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_CLSFCTN_FK FOREIGN KEY 
    ( 
     CLASSIFICATION_ID
    ) 
    REFERENCES CD_CLASSIFICATION 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_LNG_FK FOREIGN KEY 
    ( 
     LANGUAGE_ID
    ) 
    REFERENCES CD_LANGUAGE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_USER_FK FOREIGN KEY 
    ( 
     USER_ID
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_USER_HR_ADVISOR_FK FOREIGN KEY 
    ( 
     USER_ID_HR_ADVISOR
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_WFASTS_FK FOREIGN KEY 
    ( 
     WFA_STATUS_ID
    ) 
    REFERENCES CD_WFA_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_WRKUNT_FK FOREIGN KEY 
    ( 
     WORK_UNIT_ID
    ) 
    REFERENCES CD_WORK_UNIT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CD_APPOINTMENT_NON_ADVERTISED_FK FOREIGN KEY 
    ( 
     APPOINTMENT_NON_ADVERTISED_ID
    ) 
    REFERENCES CD_APPOINTMENT_NON_ADVERTISED 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CD_SELECTION_PROCESS_TYPE_FK FOREIGN KEY 
    ( 
     SELECTION_PROCESS_TYPE_ID
    ) 
    REFERENCES CD_SELECTION_PROCESS_TYPE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CD_WORK_SCHEDULE_FK FOREIGN KEY 
    ( 
     WORK_SCHEDULE_ID
    ) 
    REFERENCES CD_WORK_SCHEDULE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CDRSTS_FK FOREIGN KEY 
    ( 
     REQUEST_STATUS_ID
    ) 
    REFERENCES CD_REQUEST_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CLSFCTN_FK FOREIGN KEY 
    ( 
     CLASSIFICATION_ID
    ) 
    REFERENCES CD_CLASSIFICATION 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_EMPTNR_FK FOREIGN KEY 
    ( 
     EMPLOYMENT_TENURE_ID
    ) 
    REFERENCES CD_EMPLOYMENT_TENURE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_LNG_FK FOREIGN KEY 
    ( 
     LANGUAGE_ID
    ) 
    REFERENCES CD_LANGUAGE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_LNGRQR_FK FOREIGN KEY 
    ( 
     LANGUAGE_REQUIREMENT_ID
    ) 
    REFERENCES CD_LANGUAGE_REQUIREMENT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_SCRCLNC_FK FOREIGN KEY 
    ( 
     SECURITY_CLEARANCE_ID
    ) 
    REFERENCES CD_SECURITY_CLEARANCE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_HIRING_MANAGER_FK FOREIGN KEY 
    ( 
     USER_ID_HIRING_MANAGER
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_HR_ADVISOR_FK FOREIGN KEY 
    ( 
     USER_ID_HR_ADVISOR
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_SUB_DELEGATED_MANAGER_FK FOREIGN KEY 
    ( 
     USER_ID_SUB_DELEGATED_MANAGER
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_SUBMITTER_FK FOREIGN KEY 
    ( 
     USER_ID_SUBMITTER
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_WRKUNT_FK FOREIGN KEY 
    ( 
     WORK_UNIT_ID
    ) 
    REFERENCES CD_WORK_UNIT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_CITY 
    ADD CONSTRAINT RQSTCTY_CITY_FK FOREIGN KEY 
    ( 
     CITY_ID
    ) 
    REFERENCES CD_CITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_CITY 
    ADD CONSTRAINT RQSTCTY_REQUEST_FK FOREIGN KEY 
    ( 
     REQUEST_ID
    ) 
    REFERENCES REQUEST 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_EMPLOYMENT_EQUITY 
    ADD CONSTRAINT RQSTEMPLYMNTEQT_EMPLYMNTEQT_FK FOREIGN KEY 
    ( 
     EMPLOYMENT_EQUITY_ID
    ) 
    REFERENCES CD_EMPLOYMENT_EQUITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_EMPLOYMENT_EQUITY 
    ADD CONSTRAINT RQSTEMPLYMNTEQT_REQUEST_FK FOREIGN KEY 
    ( 
     REQUEST_ID
    ) 
    REFERENCES REQUEST 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE [USER] 
    ADD CONSTRAINT USER_LNG_FK FOREIGN KEY 
    ( 
     LANGUAGE_ID
    ) 
    REFERENCES CD_LANGUAGE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE [USER] 
    ADD CONSTRAINT USER_USERTYP_FK FOREIGN KEY 
    ( 
     USER_TYPE_ID
    ) 
    REFERENCES CD_USER_TYPE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE CD_WORK_UNIT 
    ADD CONSTRAINT WRKUNT_WRKUNT_FK FOREIGN KEY 
    ( 
     PARENT_WORK_UNIT_ID
    ) 
    REFERENCES CD_WORK_UNIT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;
