apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vacman-backend
  labels:
    app.kubernetes.io/name: vacman-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: DYNATRACE_API_KEY
      remoteRef: { key: shared, property: DYNATRACE_API_KEY }
    - secretKey: GCNOTIFY_API_KEY
      remoteRef: { key: shared, property: DYNATRACE_API_KEY }
  target:
    template:
      data:
        APPLICATION_GCNOTIFY_API_KEY: '{{ .GCNOTIFY_API_KEY }}'
        MANAGEMENT_OTLP_METRICS_EXPORT_HEADERS_AUTHORIZATION: 'Api-Token {{ .DYNATRACE_API_KEY }}'