apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: dev
labels:
  - pairs:
      app.kubernetes.io/part-of: vacancy-management
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: dev
      app.kubernetes.io/tier: nonprod
resources:
  - ../../base/vacman-backend/
  - ../../base/vacman-frontend/
  - ./external-secrets.yaml
  - ./ingresses.yaml
patches:
  - path: ./patches/deployments-backend.yaml
  - path: ./patches/deployments-frontend.yaml
configMapGenerator:
  - name: vacman-frontend
    behavior: create
    envs:
    - ./configs/vacman-frontend.conf
  - name: vacman-backend-configmap
    behavior: create
    files:
    - application.yaml=./configs/vacman-backend.yaml
