apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vacman-backend
  labels:
    app.kubernetes.io/name: vacman-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vacman-backend
  minReplicas: 2
  maxReplicas: 64
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vacman-frontend
  labels:
    app.kubernetes.io/name: vacman-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vacman-frontend
  minReplicas: 2
  maxReplicas: 64
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
