apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacman-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vacman-backend
  template:
    spec:
      containers:
        - name: vacman-backend
          envFrom:
            - secretRef:
                name: vacman-backend-int