apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacman-frontend
  annotations:
    secret.reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vacman-frontend
  template:
    spec:
      containers:
        - name: vacman-frontend
          envFrom:
            - configMapRef:
                name: vacman-frontend-int
            - secretRef:
                name: vacman-frontend-int
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-shared
                  key: REDIS_PASSWORD