--liquibase formatted sql

--changeset system:request_language_requirement dbms:mssql,h2 logicalFilePath:BOOT-INF/classes/db/changelog/changes/000010.languageRequirement.sql
CREATE TABLE REQUEST_LANGUAGE_REQUIREMENT
(
	ID BIGINT NOT NULL IDENTITY,
	LANGUAGE_REQUIREMENT_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)

);

--changeset system:mssql-h2-modify dbms:mssql,h2 logicalFilePath:BOOT-INF/classes/db/changelog/changes/000010.languageRequirement.sql
ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD DATE_UPDATED DATETIMEOFFSET;

--changeset system:mssql-modify dbms:mssql logicalFilePath:BOOT-INF/classes/db/changelog/changes/000010.languageRequirement.sql
EXEC sp_addextendedproperty 'MS_Description' , 'The REQUEST_LANGUAGE_REQUIREMENT table is an association table between CD_LANGUAGE_REQUIREMENT and REQUEST.' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST_LANGUAGE_REQUIREMENT' ;

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD CONSTRAINT RQSTLNGRQR_PK PRIMARY KEY CLUSTERED (ID)
    WITH (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS = ON );

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD CONSTRAINT RQSTLNGRQR_UK UNIQUE NONCLUSTERED (LANGUAGE_REQUIREMENT_ID, REQUEST_ID);

--changeset system:h2-modify dbms:h2 logicalFilePath:BOOT-INF/classes/db/changelog/changes/000010.languageRequirement.sql
ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT
  ADD CONSTRAINT RQSTLNGRQR_LNGRQR_FK FOREIGN KEY
  (
    LANGUAGE_REQUIREMENT_ID
  )
  REFERENCES CD_LANGUAGE_REQUIREMENT
  (
    ID
  )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION ;

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT
  ADD CONSTRAINT RQSTLNGRQR_REQUEST_FK FOREIGN KEY
  (
    REQUEST_ID
  )
  REFERENCES REQUEST
  (
    ID
  )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION ;

--changeset system:request_language_requirement_adding_preexisting_language_requirements dbms:mssql,h2 logicalFilePath:BOOT-INF/classes/db/changelog/changes/000010.languageRequirement.sql
INSERT INTO REQUEST_LANGUAGE_REQUIREMENT
  (LANGUAGE_REQUIREMENT_ID, REQUEST_ID, USER_CREATED, DATE_CREATED)
SELECT
  lang.ID,
  req.ID,
  'system' AS USER_CREATED,
  GETDATE() AS DATE_CREATED
FROM REQUEST req
JOIN CD_LANGUAGE_REQUIREMENT lang
  ON req.LANGUAGE_REQUIREMENT_ID = lang.ID;
