--liquibase formatted sql

--changeset system:mssql-modify dbms:mssql logicalFilePath:BOOT-INF/classes/db/changelog/changes/mssql/db.mssql.v1.init.sql
EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information related to the reasons for appointments that are made through a Non-Advertised Process. It specifically applies to appointments categorized as either External or Internal Non-Advertised.' , 'USER' , 'dbo' , 'TABLE' , 'CD_APPOINTMENT_NON_ADVERTISED' ;

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL; 

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD DATE_UPDATED DATETIMEOFFSET;
 
ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD CONSTRAINT APPNTMNTNONADVRTSD_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_APPOINTMENT_NON_ADVERTISED ADD CONSTRAINT APPNTMNTNONADVRTSD_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains standardized information about Canadian cities, including an association to the corresponding province to which each city belongs.' , 'USER' , 'dbo' , 'TABLE' , 'CD_CITY' ;

ALTER TABLE CD_CITY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_CITY ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_CITY ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_CITY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();  
 
ALTER TABLE CD_CITY ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_CITY ADD CONSTRAINT CITY_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_CITY ADD CONSTRAINT CITY_UK UNIQUE NONCLUSTERED (CODE, PROVINCE_TERRITORY_ID, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains standardized classifications used in the federal government of Canada. It includes information about occupational groups and levels used for human resources management.' , 'USER' , 'dbo' , 'TABLE' , 'CD_CLASSIFICATION' ;
 
ALTER TABLE CD_CLASSIFICATION ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_CLASSIFICATION ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_CLASSIFICATION ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_CLASSIFICATION ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_CLASSIFICATION ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_CLASSIFICATION ADD CONSTRAINT CLSFCTN_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_CLASSIFICATION ADD CONSTRAINT CLSFCTN_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table provides information related to Employment Equity categories. It is intended for use when an organizational requirement for employment equity has been identified in the context of a staffing process, deployment, or appointment.' , 'USER' , 'dbo' , 'TABLE' , 'CD_EMPLOYMENT_EQUITY' ;
 
ALTER TABLE CD_EMPLOYMENT_EQUITY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE(); 

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD CONSTRAINT EMPLYMNTEQT_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_EMPLOYMENT_EQUITY ADD CONSTRAINT EMPLYMNTEQT_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information related to Employment Opportunities.' , 'USER' , 'dbo' , 'TABLE' , 'CD_EMPLOYMENT_OPPORTUNITY' ;

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD DATE_UPDATED DATETIMEOFFSET; 

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT EMPOPPR_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT EMPOPPR_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table defines employment tenure types used in employee referral requests.' , 'USER' , 'dbo' , 'TABLE' , 'CD_EMPLOYMENT_TENURE' ;

ALTER TABLE CD_EMPLOYMENT_TENURE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_EMPLOYMENT_TENURE ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_EMPLOYMENT_TENURE ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_EMPLOYMENT_TENURE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_EMPLOYMENT_TENURE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_EMPLOYMENT_TENURE ADD CONSTRAINT EMPTNR_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_EMPLOYMENT_TENURE ADD CONSTRAINT EMPTNR_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the two official languages of the Government of Canada available for users of the application.' , 'USER' , 'dbo' , 'TABLE' , 'CD_LANGUAGE' ;

ALTER TABLE CD_LANGUAGE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_LANGUAGE ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_LANGUAGE ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_LANGUAGE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_LANGUAGE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_LANGUAGE ADD CONSTRAINT LNG_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_LANGUAGE ADD CONSTRAINT LNG_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the language profiles for which users may wish to be referred.' , 'USER' , 'dbo' , 'TABLE' , 'CD_LANGUAGE_REFERRAL_TYPE' ;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT LNGRFRTYP_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT LNGRFRTYP_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the language requirements associated with a request.' , 'USER' , 'dbo' , 'TABLE' , 'CD_LANGUAGE_REQUIREMENT' ;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD CONSTRAINT LNGRQR_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_LANGUAGE_REQUIREMENT ADD CONSTRAINT LNGRQR_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information related to Match Statuses.' , 'USER' , 'dbo' , 'TABLE' , 'CD_MATCH_STATUS' ;

ALTER TABLE CD_MATCH_STATUS ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_MATCH_STATUS ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_MATCH_STATUS ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_MATCH_STATUS ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_MATCH_STATUS ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_MATCH_STATUS ADD CONSTRAINT MTCHSTS_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_MATCH_STATUS ADD CONSTRAINT MTCHSTS_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);



EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information related to Match Feedback' , 'USER' , 'dbo' , 'TABLE' , 'CD_MATCH_FEEDBACK';

ALTER TABLE CD_MATCH_FEEDBACK ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_MATCH_FEEDBACK ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_MATCH_FEEDBACK ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_MATCH_FEEDBACK ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_MATCH_FEEDBACK ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_MATCH_FEEDBACK ADD CONSTRAINT MTCHFDBCK_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_MATCH_FEEDBACK ADD CONSTRAINT MTCHFDBCK_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the various statuses that a user profile can hold within the application.' , 'USER' , 'dbo' , 'TABLE' , 'CD_PROFILE_STATUS' ;

ALTER TABLE CD_PROFILE_STATUS ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_PROFILE_STATUS ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_PROFILE_STATUS ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_PROFILE_STATUS ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_PROFILE_STATUS ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_PROFILE_STATUS ADD CONSTRAINT PRFLSTS_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_PROFILE_STATUS ADD CONSTRAINT PRFLSTS_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the provinces and territories of Canada.' , 'USER' , 'dbo' , 'TABLE' , 'CD_PROVINCE_TERRITORY' ;

ALTER TABLE CD_PROVINCE_TERRITORY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_PROVINCE_TERRITORY ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_PROVINCE_TERRITORY ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_PROVINCE_TERRITORY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_PROVINCE_TERRITORY ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_PROVINCE_TERRITORY ADD CONSTRAINT PRVNCTRY_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_PROVINCE_TERRITORY ADD CONSTRAINT PRVNCTRY_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the various statuses of requests within the application.' , 'USER' , 'dbo' , 'TABLE' , 'CD_REQUEST_STATUS' ;

ALTER TABLE CD_REQUEST_STATUS ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_REQUEST_STATUS ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_REQUEST_STATUS ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_REQUEST_STATUS ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_REQUEST_STATUS ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_REQUEST_STATUS ADD CONSTRAINT RQSTSTS_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_REQUEST_STATUS ADD CONSTRAINT RQSTSTS_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the different levels of security clearance required for the request.' , 'USER' , 'dbo' , 'TABLE' , 'CD_SECURITY_CLEARANCE' ;

ALTER TABLE CD_SECURITY_CLEARANCE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_SECURITY_CLEARANCE ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_SECURITY_CLEARANCE ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_SECURITY_CLEARANCE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_SECURITY_CLEARANCE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_SECURITY_CLEARANCE ADD CONSTRAINT SCRCLNC_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_SECURITY_CLEARANCE ADD CONSTRAINT SCRCLNC_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information about the various types of selection processes applicable to indeterminate and term positions only.' , 'USER' , 'dbo' , 'TABLE' , 'CD_SELECTION_PROCESS_TYPE' ;

ALTER TABLE CD_SELECTION_PROCESS_TYPE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD DATE_UPDATED DATETIMEOFFSET; 

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD CONSTRAINT SLCTNPRCSSTYP_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_SELECTION_PROCESS_TYPE ADD CONSTRAINT SLCTNPRCSSTYP_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the three types of users within the application: Employees, Hiring Managers, and HR Advisors.' , 'USER' , 'dbo' , 'TABLE' , 'CD_USER_TYPE' ;

ALTER TABLE CD_USER_TYPE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_USER_TYPE ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_USER_TYPE ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_USER_TYPE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_USER_TYPE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_USER_TYPE ADD CONSTRAINT USERTYP_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_USER_TYPE ADD CONSTRAINT USERTYP_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the current Workforce Adjustment (WFA) status.' , 'USER' , 'dbo' , 'TABLE' , 'CD_WFA_STATUS' ;

ALTER TABLE CD_WFA_STATUS ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_WFA_STATUS ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_WFA_STATUS ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_WFA_STATUS ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_WFA_STATUS ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_WFA_STATUS ADD CONSTRAINT WFASTS_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_WFA_STATUS ADD CONSTRAINT WFASTS_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the different work schedules available in a request.' , 'USER' , 'dbo' , 'TABLE' , 'CD_WORK_SCHEDULE' ;

ALTER TABLE CD_WORK_SCHEDULE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_WORK_SCHEDULE ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_WORK_SCHEDULE ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_WORK_SCHEDULE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_WORK_SCHEDULE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_WORK_SCHEDULE ADD CONSTRAINT WRKSCHDL_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_WORK_SCHEDULE ADD CONSTRAINT WRKSCHDL_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'This code table contains information regarding the various work units within ESDC, specifically categorizing them by branch and region.' , 'USER' , 'dbo' , 'TABLE' , 'CD_WORK_UNIT' ;

ALTER TABLE CD_WORK_UNIT ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CD_WORK_UNIT ADD EFFECTIVE_DATE DATETIMEOFFSET NOT NULL;

ALTER TABLE CD_WORK_UNIT ADD EXPIRY_DATE DATETIMEOFFSET;

ALTER TABLE CD_WORK_UNIT ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CD_WORK_UNIT ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CD_WORK_UNIT ADD CONSTRAINT WRKUNT_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CD_WORK_UNIT ADD CONSTRAINT WRKUNT_UK UNIQUE NONCLUSTERED (CODE, EXPIRY_DATE);


EXEC sp_addextendedproperty 'MS_Description' , 'The PROFILE_CITY table is an association table between CD_CITY and PROFILE.' , 'USER' , 'dbo' , 'TABLE' , 'PROFILE_CITY' ;

ALTER TABLE PROFILE_CITY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE PROFILE_CITY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE_CITY ADD DATE_UPDATED DATETIMEOFFSET; 

ALTER TABLE PROFILE_CITY ADD CONSTRAINT PRFLCTY_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE PROFILE_CITY ADD CONSTRAINT PRFLCTY_UK UNIQUE NONCLUSTERED (PROFILE_ID, CITY_ID);


EXEC sp_addextendedproperty 'MS_Description' , 'The CLASSIFICATION_PROFILE table is an association table between CD_CLASSIFICATION and PROFILE.' , 'USER' , 'dbo' , 'TABLE' , 'CLASSIFICATION_PROFILE' ;

ALTER TABLE CLASSIFICATION_PROFILE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE CLASSIFICATION_PROFILE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE CLASSIFICATION_PROFILE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE CLASSIFICATION_PROFILE ADD CONSTRAINT CLSPRFL_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE CLASSIFICATION_PROFILE ADD CONSTRAINT CLSPRFL_UK UNIQUE NONCLUSTERED (CLASSIFICATION_ID, PROFILE_ID);


ALTER TABLE EVENT ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE EVENT ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE EVENT ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE EVENT ADD CONSTRAINT EVENT_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );


EXEC sp_addextendedproperty 'MS_Description' , 'The MATCH table is an association table between PROFILE and REQUEST.' , 'USER' , 'dbo' , 'TABLE' , 'MATCH' ;

ALTER TABLE MATCH ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE MATCH ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE MATCH ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE MATCH ADD CONSTRAINT MATCH_PK PRIMARY KEY CLUSTERED (ID)
     WITH (

     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );


EXEC sp_addextendedproperty 'MS_Description' , 'This table contains all the associated profile information for the Profile section of the application.' , 'USER' , 'dbo' , 'TABLE' , 'PROFILE' ;

ALTER TABLE PROFILE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE PROFILE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE PROFILE ADD CONSTRAINT PROFILE_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );


EXEC sp_addextendedproperty 'MS_Description' , 'The PROFILE_EMPLOYMENT_OPPORTUNITY table is an association table between CD_EMPLOYMENT_OPPORTUNITY and PROFILE.' , 'USER' , 'dbo' , 'TABLE' , 'PROFILE_EMPLOYMENT_OPPORTUNITY' ;

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT PEMPOPPR_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY ADD CONSTRAINT PEMPOPPR_UK UNIQUE NONCLUSTERED (EMPLOYMENT_OPPORTUNITY_ID, PROFILE_ID);


EXEC sp_addextendedproperty 'MS_Description' , 'The PROFILE_LANGUAGE_REFERRAL_TYPE table is an association table between CD_LANGUAGE_REFERRAL_TYPE and PROFILE.' , 'USER' , 'dbo' , 'TABLE' , 'PROFILE_LANGUAGE_REFERRAL_TYPE' ;

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT PLNGRLTYP_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE ADD CONSTRAINT PLNGRLTYP_UK UNIQUE NONCLUSTERED (PROFILE_ID, LANGUAGE_REFERRAL_TYPE_ID);


EXEC sp_addextendedproperty 'MS_Description' , 'This table contains all the associated request information for the Request section of the application.' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST' ;

ALTER TABLE REQUEST ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE REQUEST ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE REQUEST ADD CONSTRAINT REQUEST_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

EXEC sp_addextendedproperty 'MS_Description' , 'Approval received from the Workforce Management Committee (Non-EX positions) or the People Management Leadership Committee (EX positions).' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST' , 'COLUMN' , 'APPR_RCV_WMC_PMLC_IND';

EXEC sp_addextendedproperty 'MS_Description' , 'Would the appointment of a priority person result in a priority entitlement for another indeterminate employee? (Yes / No)' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST' , 'COLUMN' , 'APPT_RSLT_PRRT_ENTTLMNT_IND';

EXEC sp_addextendedproperty 'MS_Description' , 'If yes, please provide the rationale. (text box)' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST' , 'COLUMN' , 'APPT_RSLT_PRRT_ENTTLMNT_RTNL';

EXEC sp_addextendedproperty 'MS_Description' , 'Has the person proposed previously performed the same duties in the last twelve months or is this person still currently performing them in any capacity (casual, Interchange Canada, agency, contractor, acting more than four months, etc.)?
(Yes / No)' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST' , 'COLUMN' , 'HAS_PRVS_PRFRMD_DTS_IND';

EXEC sp_addextendedproperty 'MS_Description' , 'The REQUEST_CITY table is an association table between CD_CITY and REQUEST.' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST_CITY' ;

ALTER TABLE REQUEST_CITY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE REQUEST_CITY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST_CITY ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE REQUEST_CITY ADD CONSTRAINT RQSTCTY_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE REQUEST_CITY ADD CONSTRAINT RQSTCTY_UK UNIQUE NONCLUSTERED (CITY_ID, REQUEST_ID);


EXEC sp_addextendedproperty 'MS_Description' , 'The REQUEST_EMPLOYMENT_EQUITY table is an association table between CD_EMPLOYMENT_EQUITY and REQUEST.' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST_EMPLOYMENT_EQUITY' ;

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD CONSTRAINT RQSTEMPLYMNTEQT_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE REQUEST_EMPLOYMENT_EQUITY ADD CONSTRAINT RQSTEMPLYMNTEQT_UK UNIQUE NONCLUSTERED (EMPLOYMENT_EQUITY_ID, REQUEST_ID);


EXEC sp_addextendedproperty 'MS_Description' , 'This table contains all the associated user information for the User section of the application.' , 'USER' , 'dbo' , 'TABLE' , 'USER' ;

ALTER TABLE [USER] ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE [USER] ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE [USER] ADD DATE_UPDATED DATETIMEOFFSET;

ALTER TABLE [USER] ADD CONSTRAINT USER_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE [USER] ADD CONSTRAINT USER_UK UNIQUE NONCLUSTERED (MS_ENTRA_ID);


ALTER TABLE CD_CITY 
    ADD CONSTRAINT CITY_PRVNCTRY_FK FOREIGN KEY 
    ( 
     PROVINCE_TERRITORY_ID
    ) 
    REFERENCES CD_PROVINCE_TERRITORY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE CLASSIFICATION_PROFILE 
    ADD CONSTRAINT CLSPRFL_CLSFCTN_FK FOREIGN KEY 
    ( 
     CLASSIFICATION_ID
    ) 
    REFERENCES CD_CLASSIFICATION 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE CLASSIFICATION_PROFILE 
    ADD CONSTRAINT CLSPRFL_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_CITY 
    ADD CONSTRAINT PRFLCTY_CITY_FK FOREIGN KEY 
    ( 
     CITY_ID
    ) 
    REFERENCES CD_CITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_CITY 
    ADD CONSTRAINT PRFLCTY_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE MATCH 
    ADD CONSTRAINT MATCH_MTCHFDBCK_FK FOREIGN KEY 
    ( 
     MATCH_FEEDBACK_ID
    ) 
    REFERENCES CD_MATCH_FEEDBACK 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE MATCH 
    ADD CONSTRAINT MATCH_MTCHSTS_FK FOREIGN KEY 
    ( 
     MATCH_STATUS_ID
    ) 
    REFERENCES CD_MATCH_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE MATCH 
    ADD CONSTRAINT MATCH_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE MATCH 
    ADD CONSTRAINT MATCH_REQUEST_FK FOREIGN KEY 
    ( 
     REQUEST_ID
    ) 
    REFERENCES REQUEST 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY 
    ADD CONSTRAINT PEMPTNR_EMPOPPR_FK FOREIGN KEY 
    ( 
     EMPLOYMENT_OPPORTUNITY_ID
    ) 
    REFERENCES CD_EMPLOYMENT_OPPORTUNITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_EMPLOYMENT_OPPORTUNITY 
    ADD CONSTRAINT PEMPTNR_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE 
    ADD CONSTRAINT PLNGRLTYP_LNGRFRTYP_FK FOREIGN KEY 
    ( 
     LANGUAGE_REFERRAL_TYPE_ID
    ) 
    REFERENCES CD_LANGUAGE_REFERRAL_TYPE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE 
    ADD CONSTRAINT PLNGRLTYP_PROFILE_FK FOREIGN KEY 
    ( 
     PROFILE_ID
    ) 
    REFERENCES PROFILE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_CDPRSTS_FK FOREIGN KEY 
    ( 
     PROFILE_STATUS_ID
    ) 
    REFERENCES CD_PROFILE_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_CITY_FK FOREIGN KEY 
    ( 
     CITY_ID
    ) 
    REFERENCES CD_CITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_CLSFCTN_FK FOREIGN KEY 
    ( 
     CLASSIFICATION_ID
    ) 
    REFERENCES CD_CLASSIFICATION 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_LNG_FK FOREIGN KEY 
    ( 
     LANGUAGE_ID
    ) 
    REFERENCES CD_LANGUAGE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_USER_FK FOREIGN KEY 
    ( 
     USER_ID
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_USER_HR_ADVISOR_FK FOREIGN KEY 
    ( 
     USER_ID_HR_ADVISOR
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_WFASTS_FK FOREIGN KEY 
    ( 
     WFA_STATUS_ID
    ) 
    REFERENCES CD_WFA_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE PROFILE 
    ADD CONSTRAINT PROFILE_WRKUNT_FK FOREIGN KEY 
    ( 
     WORK_UNIT_ID
    ) 
    REFERENCES CD_WORK_UNIT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CD_APPOINTMENT_NON_ADVERTISED_FK FOREIGN KEY 
    ( 
     APPOINTMENT_NON_ADVERTISED_ID
    ) 
    REFERENCES CD_APPOINTMENT_NON_ADVERTISED 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CD_SELECTION_PROCESS_TYPE_FK FOREIGN KEY 
    ( 
     SELECTION_PROCESS_TYPE_ID
    ) 
    REFERENCES CD_SELECTION_PROCESS_TYPE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CD_WORK_SCHEDULE_FK FOREIGN KEY 
    ( 
     WORK_SCHEDULE_ID
    ) 
    REFERENCES CD_WORK_SCHEDULE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CDRSTS_FK FOREIGN KEY 
    ( 
     REQUEST_STATUS_ID
    ) 
    REFERENCES CD_REQUEST_STATUS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_CLSFCTN_FK FOREIGN KEY 
    ( 
     CLASSIFICATION_ID
    ) 
    REFERENCES CD_CLASSIFICATION 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_EMPTNR_FK FOREIGN KEY 
    ( 
     EMPLOYMENT_TENURE_ID
    ) 
    REFERENCES CD_EMPLOYMENT_TENURE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_LNG_FK FOREIGN KEY 
    ( 
     LANGUAGE_ID
    ) 
    REFERENCES CD_LANGUAGE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_LNGRQR_FK FOREIGN KEY 
    ( 
     LANGUAGE_REQUIREMENT_ID
    ) 
    REFERENCES CD_LANGUAGE_REQUIREMENT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_SCRCLNC_FK FOREIGN KEY 
    ( 
     SECURITY_CLEARANCE_ID
    ) 
    REFERENCES CD_SECURITY_CLEARANCE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_HIRING_MANAGER_FK FOREIGN KEY 
    ( 
     USER_ID_HIRING_MANAGER
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_HR_ADVISOR_FK FOREIGN KEY 
    ( 
     USER_ID_HR_ADVISOR
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_SUB_DELEGATED_MANAGER_FK FOREIGN KEY 
    ( 
     USER_ID_SUB_DELEGATED_MANAGER
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_USER_SUBMITTER_FK FOREIGN KEY 
    ( 
     USER_ID_SUBMITTER
    ) 
    REFERENCES [USER] 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST 
    ADD CONSTRAINT REQUEST_WRKUNT_FK FOREIGN KEY 
    ( 
     WORK_UNIT_ID
    ) 
    REFERENCES CD_WORK_UNIT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_CITY 
    ADD CONSTRAINT RQSTCTY_CITY_FK FOREIGN KEY 
    ( 
     CITY_ID
    ) 
    REFERENCES CD_CITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_CITY 
    ADD CONSTRAINT RQSTCTY_REQUEST_FK FOREIGN KEY 
    ( 
     REQUEST_ID
    ) 
    REFERENCES REQUEST 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_EMPLOYMENT_EQUITY 
    ADD CONSTRAINT RQSTEMPLYMNTEQT_EMPLYMNTEQT_FK FOREIGN KEY 
    ( 
     EMPLOYMENT_EQUITY_ID
    ) 
    REFERENCES CD_EMPLOYMENT_EQUITY 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE REQUEST_EMPLOYMENT_EQUITY 
    ADD CONSTRAINT RQSTEMPLYMNTEQT_REQUEST_FK FOREIGN KEY 
    ( 
     REQUEST_ID
    ) 
    REFERENCES REQUEST 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE [USER] 
    ADD CONSTRAINT USER_LNG_FK FOREIGN KEY 
    ( 
     LANGUAGE_ID
    ) 
    REFERENCES CD_LANGUAGE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE [USER] 
    ADD CONSTRAINT USER_USERTYP_FK FOREIGN KEY 
    ( 
     USER_TYPE_ID
    ) 
    REFERENCES CD_USER_TYPE 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;


ALTER TABLE CD_WORK_UNIT 
    ADD CONSTRAINT WRKUNT_WRKUNT_FK FOREIGN KEY 
    ( 
     PARENT_WORK_UNIT_ID
    ) 
    REFERENCES CD_WORK_UNIT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;
