--liquibase formatted sql

--changeset system:request_language_requirement dbms:mssql,h2 
CREATE TABLE REQUEST_LANGUAGE_REQUIREMENT
(
	ID BIGINT NOT NULL IDENTITY,
	LANGUAGE_REQUIREMENT_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD DATE_CREATED DATETIMEOFFSET NOT NULL DEFAULT GETDATE();

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD DATE_UPDATED DATETIMEOFFSET;

--changeset system:request_language_requirement_h2 dbms:h2
ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD CONSTRAINT RQLANG_PK PRIMARY KEY (ID);

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD CONSTRAINT RQLANG_UK UNIQUE (LANGUAGE_REQUIREMENT_ID, REQUEST_ID);

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT
  ADD CONSTRAINT RQSTLNGRQR_LNGRQR_FK FOREIGN KEY
  (
    LANGUAGE_REQUIREMENT_ID
  )
  REFERENCES CD_LANGUAGE_REQUIREMENT
  (
    ID
  )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION ;

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT
  ADD CONSTRAINT RQSTLNGRQR_REQUEST_FK FOREIGN KEY
  (
    REQUEST_ID
  )
  REFERENCES REQUEST
  (
    ID
  )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION ;

--changeset system:request_language_requirement_mssql dbms:mssql
EXEC sp_addextendedproperty 'MS_Description' , 'The REQUEST_LANGUAGE_REQUIREMENT table is an association table between CD_LANGUAGE_REQUIREMENT and REQUEST.' , 'USER' , 'dbo' , 'TABLE' , 'REQUEST_LANGUAGE_REQUIREMENT' ;

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD CONSTRAINT RQSTLNGRQR_PK PRIMARY KEY CLUSTERED (ID)
    WITH (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS = ON );

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD CONSTRAINT RQSTLNGRQR_UK UNIQUE NONCLUSTERED (LANGUAGE_REQUIREMENT_ID, REQUEST_ID);

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ALTER COLUMN ID ADD NOT FOR REPLICATION;

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT ADD CONSTRAINT RQLANG_UK UNIQUE NONCLUSTERED (LANGUAGE_REQUIREMENT_ID, REQUEST_ID);

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT 
    ADD CONSTRAINT RQLANG_REQUEST_FK FOREIGN KEY 
    ( 
     REQUEST_ID
    ) 
    REFERENCES REQUEST 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE REQUEST_LANGUAGE_REQUIREMENT 
    ADD CONSTRAINT RQLANG_LANGUAGE_REQUIREMENT_FK FOREIGN KEY 
    ( 
     LANGUAGE_REQUIREMENT_ID
    ) 
    REFERENCES CD_LANGUAGE_REQUIREMENT 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

--changeset system:request_language_requirement_adding_preexisting_language_requirements dbms:mssql,h2
INSERT INTO REQUEST_LANGUAGE_REQUIREMENT
  (LANGUAGE_REQUIREMENT_ID, REQUEST_ID, USER_CREATED, DATE_CREATED, USER_UPDATED, DATE_UPDATED)
SELECT
  req.LANGUAGE_REQUIREMENT_ID,
  req.ID,
  req.USER_CREATED,
  req.DATE_CREATED,
  req.USER_UPDATED,
  req.DATE_UPDATED
FROM REQUEST req
WHERE LANGUAGE_REQUIREMENT_ID IS NOT NULL;


