--liquibase formatted sql

--changeset your.name:1
CREATE TABLE CD_ASSESSMENT_RESULT
(
    ASSESSMENT_RESULT_ID NUMERIC (6) NOT NULL IDENTITY,
    ASSESSMENT_RESULT_CODE VARCHAR (20) NOT NULL,
    ASSESSMENT_RESULT_NAME_EN VARCHAR (100) NOT NULL,
    ASSESSMENT_RESULT_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

-- ALTER TABLE CD_ASSESSMENT_RESULT ADD CONSTRAINT ASMNTRSLT_UK UNIQUE NONCLUSTERED (ASSESSMENT_RESULT_NAME_EN);

CREATE TABLE CD_CITY
(
    CITY_ID NUMERIC (6) NOT NULL IDENTITY,
    PROVINCE_TERRITORY_ID NUMERIC (6) NOT NULL,
    CITY_CODE VARCHAR (20) NOT NULL,
    CITY_NAME_EN VARCHAR (100) NOT NULL,
    CITY_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_CLASSIFICATION
(
    CLASSIFICATION_ID NUMERIC (6) NOT NULL IDENTITY,
    CLASSIFICATION_CODE VARCHAR (20) NOT NULL,
    CLASSIFICATION_NAME_EN VARCHAR (100) NOT NULL,
    CLASSIFICATION_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_EDUCATION_LEVEL
(
    EDUCATION_LEVEL_ID NUMERIC (6) NOT NULL IDENTITY,
    EDUCATION_LEVEL_CODE VARCHAR (20) NOT NULL,
    EDUCATION_LEVEL_NAME_EN VARCHAR (100) NOT NULL,
    EDUCATION_LEVEL_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_EMPLOYMENT_TENURE
(
    EMPLOYMENT_TENURE_ID NUMERIC (6) NOT NULL IDENTITY,
    EMPLOYMENT_TENURE_CODE VARCHAR (20) NOT NULL,
    EMPLOYMENT_TENURE_NAME_EN VARCHAR (100) NOT NULL,
    EMPLOYMENT_TENURE_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_LANGUAGE
(
    LANGUAGE_ID NUMERIC (6) NOT NULL IDENTITY,
    LANGUAGE_CODE VARCHAR (20) NOT NULL,
    LANGUAGE_NAME_EN VARCHAR (100) NOT NULL,
    LANGUAGE_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_LANGUAGE_REFERRAL_TYPE
(
    LANGUAGE_REFERRAL_TYPE_ID NUMERIC (6) NOT NULL IDENTITY,
    LANGUAGE_REFERRAL_TYPE_CODE VARCHAR (20) NOT NULL,
    LANGUAGE_REFERRAL_TYPE_NAME_EN VARCHAR (100) NOT NULL,
    LANGUAGE_REFERRAL_TYPE_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_NOTIFICATION_PURPOSE
(
    NOTIFICATION_PURPOSE_ID NUMERIC (6) NOT NULL IDENTITY,
    NOTIFICATION_PURPOSE_CODE VARCHAR (20) NOT NULL,
    NOTIFICATION_PURPOSE_NAME_EN VARCHAR (100) NOT NULL,
    NOTIFICATION_PURPOSE_NAME_FR VARCHAR (100) NOT NULL,
    GC_NOTIFY_TEMPLATE_ID VARCHAR (36) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_PRIORITY_LEVEL
(
    PRIORITY_LEVEL_ID NUMERIC (6) NOT NULL IDENTITY,
    PRIORITY_LEVEL_CODE VARCHAR (20) NOT NULL,
    PRIORITY_LEVEL_NAME_EN VARCHAR (100) NOT NULL,
    PRIORITY_LEVEL_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_PROFILE_STATUS
(
    PROFILE_STATUS_ID NUMERIC (6) NOT NULL IDENTITY,
    PROFILE_STATUS_CODE VARCHAR (20) NOT NULL,
    PROFILE_STATUS_NAME_EN VARCHAR (100) NOT NULL,
    PROFILE_STATUS_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_PROVINCE_TERRITORY
(
    PROVINCE_TERRITORY_ID NUMERIC (6) NOT NULL IDENTITY,
    PROVINCE_TERRITORY_CODE VARCHAR (20) NOT NULL,
    PROVINCE_TERRITORY_NAME_EN VARCHAR (100) NOT NULL,
    PROVINCE_TERRITORY_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_REQUEST_STATUS
(
    REQUEST_STATUS_ID NUMERIC (6) NOT NULL IDENTITY,
    REQUEST_STATUS_CODE VARCHAR (20) NOT NULL,
    REQUEST_STATUS_NAME_EN VARCHAR (100) NOT NULL,
    REQUEST_STATUS_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_SECURITY_CLEARANCE
(
    SECURITY_CLEARANCE_ID NUMERIC (6) NOT NULL IDENTITY,
    SECURITY_CLEARANCE_CODE VARCHAR (20) NOT NULL,
    SECURITY_CLEARANCE_NAME_EN VARCHAR (100) NOT NULL,
    SECURITY_CLEARANCE_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_USER_TYPE
(
    USER_TYPE_ID NUMERIC (6) NOT NULL IDENTITY,
    USER_TYPE_CODE VARCHAR (20) NOT NULL,
    USER_TYPE_NAME_EN VARCHAR (100) NOT NULL,
    USER_TYPE_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_WFA_STATUS
(
    WFA_STATUS_ID NUMERIC (6) NOT NULL IDENTITY,
    WFA_STATUS_CODE VARCHAR (20) NOT NULL,
    WFA_STATUS_NAME_EN VARCHAR (100) NOT NULL,
    WFA_STATUS_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CD_WORK_UNIT
(
    WORK_UNIT_ID NUMERIC (6) NOT NULL IDENTITY,
    PARENT_WORK_UNIT_ID NUMERIC (6),
    WORK_UNIT_CODE VARCHAR (20) NOT NULL,
    WORK_UNIT_NAME_EN VARCHAR (100) NOT NULL,
    WORK_UNIT_NAME_FR VARCHAR (100) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CITY_PROFILE
(
    CITY_PROFILE_ID NUMERIC (10) NOT NULL IDENTITY,
    PROFILE_ID NUMERIC (10) NOT NULL,
    CITY_ID NUMERIC (6) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE CLASSIFICATION_PROFILE
(
    CLASSIFICATION_PROFILE_ID NUMERIC (10) NOT NULL IDENTITY,
    CLASSIFICATION_ID NUMERIC (6) NOT NULL,
    PROFILE_ID NUMERIC (10) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

-- ALTER TABLE CLASSIFICATION_PROFILE ADD CONSTRAINT CLSPRFL_UK UNIQUE NONCLUSTERED (CLASSIFICATION_ID, PROFILE_ID);

CREATE TABLE EVENT
(
    EVENT_ID NUMERIC (10) NOT NULL IDENTITY,
    EVENT_NAME VARCHAR (255) NOT NULL,
    EVENT_DESCRIPTION VARCHAR (4000),
    DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_UPDATED DATETIME,
    USER_CREATED VARCHAR (50) NOT NULL,
    USER_UPDATED VARCHAR (50)
);

CREATE TABLE PROFILE
(
    PROFILE_ID NUMERIC (10) NOT NULL IDENTITY,
    USER_ID NUMERIC (10) NOT NULL,
    USER_ID_REVIEWED_BY NUMERIC (10),
    USER_ID_APPROVED_BY NUMERIC (10),
    EDUCATION_LEVEL_ID NUMERIC (6),
    WFA_STATUS_ID NUMERIC (6),
    CLASSIFICATION_ID NUMERIC (6),
    CITY_ID NUMERIC (6),
    PRIORITY_LEVEL_ID NUMERIC (6),
    WORK_UNIT_ID NUMERIC (6),
    LANGUAGE_ID NUMERIC (6),
    PROFILE_STATUS_ID NUMERIC (6) NOT NULL,
    PERSONAL_PHONE_NUMBER VARCHAR (15),
    PERSONAL_EMAIL_ADDRESS VARCHAR (320),
    PRIVACY_CONSENT_IND BIT DEFAULT 1,
    AVAILABLE_FOR_REFERRAL_IND BIT DEFAULT 1,
    INTERESTED_IN_ALTERNATION_IND BIT DEFAULT 1,
    ADDITIONAL_COMMENT_TXT VARCHAR (200),
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE PROFILE_EMPLOYMENT_TENURE
(
    PROFILE_EMPLOYMENT_TENURE_ID NUMERIC (10) NOT NULL IDENTITY,
    EMPLOYMENT_TENURE_ID NUMERIC (6) NOT NULL,
    PROFILE_ID NUMERIC (10) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE PROFILE_LANGUAGE_REFERRAL_TYPE
(
    PROFILE_LANGUAGE_REFERRAL_TYPE_ID NUMERIC (10) NOT NULL IDENTITY,
    PROFILE_ID NUMERIC (10) NOT NULL,
    LANGUAGE_REFERRAL_TYPE_ID NUMERIC (6) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE PROFILE_REQUEST 
(
    PROFILE_REQUEST_ID NUMERIC (10) NOT NULL IDENTITY,
    REQUEST_ID NUMERIC (10) NOT NULL,
    PROFILE_ID NUMERIC (10) NOT NULL,
    ASSESSMENT_RESULT_ID NUMERIC (6) NOT NULL,
    PERSON_ID_ASSESSED_BY NUMERIC (10) NOT NULL,
    PERSON_ID_APPROVED_BY NUMERIC (10) NOT NULL,
    ASSESSMENT_DATE DATE,
    ASSESSMENT_JUSTIFICATION_TEXT VARCHAR (200),
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE REQUEST
(
    REQUEST_ID NUMERIC (10) NOT NULL IDENTITY,
    SECURITY_CLEARANCE_ID NUMERIC (6) NOT NULL,
    PERSON_ID_REVIEWED_BY NUMERIC (10) NOT NULL,
    PERSON_ID_APPROVED_BY NUMERIC (10) NOT NULL,
    WORK_UNIT_ID NUMERIC (6) NOT NULL,
    CLASSIFICATION_ID NUMERIC (6) NOT NULL,
    REQUEST_STATUS_ID NUMERIC (6) NOT NULL,
    REQUEST_NAME_EN VARCHAR (200) NOT NULL,
    REQUEST_NAME_FR VARCHAR (200) NOT NULL,
    EDUCATIONAL_REQUIREMENT_TXT VARCHAR (200),
    PRIORITY_CLEARANCE_NUMBER VARCHAR (20),
    REQUEST_POSTING_DATE DATE,
    ALLOW_TELEWORK_IND BIT,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE REQUEST_CITY
(
    REQUEST_CITY_ID NUMERIC (10) NOT NULL IDENTITY,
    CITY_ID NUMERIC (6) NOT NULL,
    REQUEST_ID NUMERIC (10) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE REQUEST_EMPLOYMENT_TENURE
(
    REQUEST_EMPLOYMENT_TENURE_ID NUMERIC (10) NOT NULL IDENTITY,
    EMPLOYMENT_TENURE_ID NUMERIC (6) NOT NULL,
    REQUEST_ID NUMERIC (10) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE REQUEST_LANGUAGE_REFERRAL_TYPE
(
    REQUEST_LANGUAGE_REFERRAL_TYPE_ID NUMERIC (10) NOT NULL IDENTITY,
    REQUEST_ID NUMERIC (10) NOT NULL,
    LANGUAGE_REFERRAL_TYPE_ID NUMERIC (6) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

CREATE TABLE [USER]
(
    USER_ID NUMERIC (10) NOT NULL IDENTITY,
    USER_TYPE_ID NUMERIC (6) NOT NULL,
    LANGUAGE_ID NUMERIC (6) NOT NULL,
    NETWORK_NAME VARCHAR (50) NOT NULL,
    UU_NAME VARCHAR (50) NOT NULL,
    FIRST_NAME VARCHAR (100) NOT NULL,
    MIDDLE_NAME VARCHAR (100),
    LAST_NAME VARCHAR (100) NOT NULL,
    INITIAL VARCHAR (4),
    PERSONAL_RECORD_IDENTIFIER VARCHAR (10),
    BUSINESS_PHONE_NUMBER VARCHAR (15),
    BUSINESS_EMAIL_ADDRESS VARCHAR (320) NOT NULL,
    USER_CREATED VARCHAR (50) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    USER_UPDATED VARCHAR (50),
    DATE_UPDATED DATETIME
);

-- ALTER TABLE CD_CITY
--     ADD CONSTRAINT CITY_PRVNCTRY_FK FOREIGN KEY
--     (
--      PROVINCE_TERRITORY_ID
--     )
--     REFERENCES CD_PROVINCE_TERRITORY
--     (
--      PROVINCE_TERRITORY_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE CLASSIFICATION_PROFILE
--     ADD CONSTRAINT CLSPRFL_CLSFCTN_FK FOREIGN KEY
--     (
--      CLASSIFICATION_ID
--     )
--     REFERENCES CD_CLASSIFICATION
--     (
--      CLASSIFICATION_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE CLASSIFICATION_PROFILE
--     ADD CONSTRAINT CLSPRFL_PROFILE_FK FOREIGN KEY
--     (
--      PROFILE_ID
--     )
--     REFERENCES PROFILE
--     (
--      PROFILE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE CITY_PROFILE
--     ADD CONSTRAINT CTYPRFL_CITY_FK FOREIGN KEY
--     (
--      CITY_ID
--     )
--     REFERENCES CD_CITY
--     (
--      CITY_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE CITY_PROFILE
--     ADD CONSTRAINT CTYPRFL_PROFILE_FK FOREIGN KEY
--     (
--      PROFILE_ID
--     )
--     REFERENCES PROFILE
--     (
--      PROFILE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE_EMPLOYMENT_TENURE
--     ADD CONSTRAINT PEMPTNR_EMPTNR_FK FOREIGN KEY
--     (
--      EMPLOYMENT_TENURE_ID
--     )
--     REFERENCES CD_EMPLOYMENT_TENURE
--     (
--      EMPLOYMENT_TENURE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE_EMPLOYMENT_TENURE
--     ADD CONSTRAINT PEMPTNR_PROFILE_FK FOREIGN KEY
--     (
--      PROFILE_ID
--     )
--     REFERENCES PROFILE
--     (
--      PROFILE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE
--     ADD CONSTRAINT PLNGRLTYP_LNGRFRTYP_FK FOREIGN KEY
--     (
--      LANGUAGE_REFERRAL_TYPE_ID
--     )
--     REFERENCES CD_LANGUAGE_REFERRAL_TYPE
--     (
--      LANGUAGE_REFERRAL_TYPE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE_LANGUAGE_REFERRAL_TYPE
--     ADD CONSTRAINT PLNGRLTYP_PROFILE_FK FOREIGN KEY
--     (
--      PROFILE_ID
--     )
--     REFERENCES PROFILE
--     (
--      PROFILE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE_REQUEST
--     ADD CONSTRAINT PRFLRQST_ASMNTRSLT_FK FOREIGN KEY
--     (
--      ASSESSMENT_RESULT_ID
--     )
--     REFERENCES CD_ASSESSMENT_RESULT
--     (
--      ASSESSMENT_RESULT_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE_REQUEST
--     ADD CONSTRAINT PRFLRQST_PROFILE_FK FOREIGN KEY
--     (
--      PROFILE_ID
--     )
--     REFERENCES PROFILE
--     (
--      PROFILE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE_REQUEST
--     ADD CONSTRAINT PRFLRQST_REQUEST_FK FOREIGN KEY
--     (
--      REQUEST_ID
--     )
--     REFERENCES REQUEST
--     (
--      REQUEST_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_CDPRSTS_FK FOREIGN KEY
--     (
--      PROFILE_STATUS_ID
--     )
--     REFERENCES CD_PROFILE_STATUS
--     (
--      PROFILE_STATUS_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_CITY_FK FOREIGN KEY
--     (
--      CITY_ID
--     )
--     REFERENCES CD_CITY
--     (
--      CITY_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_CLSFCTN_FK FOREIGN KEY
--     (
--      CLASSIFICATION_ID
--     )
--     REFERENCES CD_CLASSIFICATION
--     (
--      CLASSIFICATION_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_EDCTNLVL_FK FOREIGN KEY
--     (
--      EDUCATION_LEVEL_ID
--     )
--     REFERENCES CD_EDUCATION_LEVEL
--     (
--      EDUCATION_LEVEL_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_LNG_FK FOREIGN KEY
--     (
--      LANGUAGE_ID
--     )
--     REFERENCES CD_LANGUAGE
--     (
--      LANGUAGE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_PRTYLVL_FK FOREIGN KEY
--     (
--      PRIORITY_LEVEL_ID
--     )
--     REFERENCES CD_PRIORITY_LEVEL
--     (
--      PRIORITY_LEVEL_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_USER_FK FOREIGN KEY
--     (
--      USER_ID
--     )
--     REFERENCES [USER]
--     (
--      USER_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_USER_FK2 FOREIGN KEY
--     (
--      USER_ID_REVIEWED_BY
--     )
--     REFERENCES [USER]
--     (
--      USER_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_USER_FK3 FOREIGN KEY
--     (
--      USER_ID_APPROVED_BY
--     )
--     REFERENCES [USER]
--     (
--      USER_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_WFASTS_FK FOREIGN KEY
--     (
--      WFA_STATUS_ID
--     )
--     REFERENCES CD_WFA_STATUS
--     (
--      WFA_STATUS_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE PROFILE
--     ADD CONSTRAINT PROFILE_WRKUNT_FK FOREIGN KEY
--     (
--      WORK_UNIT_ID
--     )
--     REFERENCES CD_WORK_UNIT
--     (
--      WORK_UNIT_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST_EMPLOYMENT_TENURE
--     ADD CONSTRAINT REMPTNR_EMPTNR_FK FOREIGN KEY
--     (
--      EMPLOYMENT_TENURE_ID
--     )
--     REFERENCES CD_EMPLOYMENT_TENURE
--     (
--      EMPLOYMENT_TENURE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST_EMPLOYMENT_TENURE
--     ADD CONSTRAINT REMPTNR_REQUEST_FK FOREIGN KEY
--     (
--      REQUEST_ID
--     )
--     REFERENCES REQUEST
--     (
--      REQUEST_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST
--     ADD CONSTRAINT REQUEST_CDRSTS_FK FOREIGN KEY
--     (
--      REQUEST_STATUS_ID
--     )
--     REFERENCES CD_REQUEST_STATUS
--     (
--      REQUEST_STATUS_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST
--     ADD CONSTRAINT REQUEST_CLSFCTN_FK FOREIGN KEY
--     (
--      CLASSIFICATION_ID
--     )
--     REFERENCES CD_CLASSIFICATION
--     (
--      CLASSIFICATION_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST
--     ADD CONSTRAINT REQUEST_SCRCLNC_FK FOREIGN KEY
--     (
--      SECURITY_CLEARANCE_ID
--     )
--     REFERENCES CD_SECURITY_CLEARANCE
--     (
--      SECURITY_CLEARANCE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST
--     ADD CONSTRAINT REQUEST_USER_FK FOREIGN KEY
--     (
--      PERSON_ID_REVIEWED_BY
--     )
--     REFERENCES [USER]
--     (
--      USER_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST
--     ADD CONSTRAINT REQUEST_USER_FK2 FOREIGN KEY
--     (
--      PERSON_ID_APPROVED_BY
--     )
--     REFERENCES [USER]
--     (
--      USER_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST
--     ADD CONSTRAINT REQUEST_WRKUNT_FK FOREIGN KEY
--     (
--      WORK_UNIT_ID
--     )
--     REFERENCES CD_WORK_UNIT
--     (
--      WORK_UNIT_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;


-- ALTER TABLE REQUEST_LANGUAGE_REFERRAL_TYPE
--     ADD CONSTRAINT RLNGRLTYP_LNGRFRTYP_FK FOREIGN KEY
--     (
--      LANGUAGE_REFERRAL_TYPE_ID
--     )
--     REFERENCES CD_LANGUAGE_REFERRAL_TYPE
--     (
--      LANGUAGE_REFERRAL_TYPE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST_LANGUAGE_REFERRAL_TYPE
--     ADD CONSTRAINT RLNGRLTYP_REQUEST_FK FOREIGN KEY
--     (
--      REQUEST_ID
--     )
--     REFERENCES REQUEST
--     (
--      REQUEST_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE REQUEST_CITY
--     ADD CONSTRAINT RQSTCTY_CITY_FK FOREIGN KEY
--     (
--      CITY_ID
--     )
--     REFERENCES CD_CITY
--     (
--      CITY_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;


-- ALTER TABLE REQUEST_CITY
--     ADD CONSTRAINT RQSTCTY_REQUEST_FK FOREIGN KEY
--     (
--      REQUEST_ID
--     )
--     REFERENCES REQUEST
--     (
--      REQUEST_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;


-- ALTER TABLE [USER]
--     ADD CONSTRAINT USER_LNG_FK FOREIGN KEY
--     (
--      LANGUAGE_ID
--     )
--     REFERENCES CD_LANGUAGE
--     (
--      LANGUAGE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE [USER]
--     ADD CONSTRAINT USER_USERTYP_FK FOREIGN KEY
--     (
--      USER_TYPE_ID
--     )
--     REFERENCES CD_USER_TYPE
--     (
--      USER_TYPE_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;

-- ALTER TABLE CD_WORK_UNIT
--     ADD CONSTRAINT WRKUNT_WRKUNT_FK FOREIGN KEY
--     (
--      PARENT_WORK_UNIT_ID
--     )
--     REFERENCES CD_WORK_UNIT
--     (
--      WORK_UNIT_ID
--     )
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION;