--liquibase formatted sql

--changeset system:1
CREATE TABLE CD_APPOINTMENT_NON_ADVERTISED 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (150) NOT NULL,
	NAME_FR NVARCHAR (150) NOT NULL,
	INTERNAL_IND BIT NOT NULL DEFAULT 1,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_CITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	PROVINCE_TERRITORY_ID BIGINT NOT NULL,
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_CLASSIFICATION 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_EMPLOYMENT_EQUITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_EMPLOYMENT_OPPORTUNITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_EMPLOYMENT_TENURE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_LANGUAGE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_LANGUAGE_REFERRAL_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_LANGUAGE_REQUIREMENT 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_MATCH_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_MATCH_FEEDBACK 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_PROFILE_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_PROVINCE_TERRITORY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_REQUEST_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_SECURITY_CLEARANCE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_SELECTION_PROCESS_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_USER_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_WFA_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	SORT_ORDER INTEGER,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_WORK_SCHEDULE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CD_WORK_UNIT 
(
	ID BIGINT NOT NULL IDENTITY, 
	PARENT_WORK_UNIT_ID BIGINT,
	CODE NVARCHAR (20) NOT NULL,
	NAME_EN NVARCHAR (100) NOT NULL,
	NAME_FR NVARCHAR (100) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE PROFILE_CITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	PROFILE_ID BIGINT NOT NULL,
	CITY_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE CLASSIFICATION_PROFILE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CLASSIFICATION_ID BIGINT NOT NULL,
	PROFILE_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE EVENT 
(
	ID BIGINT NOT NULL IDENTITY, 
	TYPE NVARCHAR (255) NOT NULL,
	DETAIL NVARCHAR (4000),
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE MATCH 
(
	ID BIGINT NOT NULL IDENTITY,
	PROFILE_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	MATCH_STATUS_ID BIGINT NOT NULL,
	HIRING_MANAGER_COMMENT NVARCHAR (100),
	HR_ADVISOR_COMMENT NVARCHAR (100),
	MATCH_FEEDBACK_ID BIGINT,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE PROFILE
(
	ID BIGINT NOT NULL IDENTITY,
	USER_ID BIGINT NOT NULL,
	USER_ID_HR_ADVISOR BIGINT,
	WFA_STATUS_ID BIGINT,
	CLASSIFICATION_ID BIGINT,
	CITY_ID BIGINT,
	WORK_UNIT_ID BIGINT,
	LANGUAGE_ID BIGINT,
	PROFILE_STATUS_ID BIGINT NOT NULL,
	PERSONAL_PHONE_NUMBER NVARCHAR (15),
	PERSONAL_EMAIL_ADDRESS NVARCHAR (320),
	PRIVACY_CONSENT_IND BIT DEFAULT 1,
	AVAILABLE_FOR_REFERRAL_IND BIT DEFAULT 1,
	INTERESTED_IN_ALTERNATION_IND BIT DEFAULT 1,
	ADDITIONAL_COMMENT NVARCHAR (200),
	WFA_START_DATE DATE,
	WFA_END_DATE DATE,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE PROFILE_EMPLOYMENT_OPPORTUNITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	EMPLOYMENT_OPPORTUNITY_ID BIGINT NOT NULL,
	PROFILE_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE PROFILE_LANGUAGE_REFERRAL_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	PROFILE_ID BIGINT NOT NULL,
	LANGUAGE_REFERRAL_TYPE_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE REQUEST 
(
	ID BIGINT NOT NULL IDENTITY,
	SECURITY_CLEARANCE_ID BIGINT,
	WORK_UNIT_ID BIGINT,
	CLASSIFICATION_ID BIGINT,
	REQUEST_STATUS_ID BIGINT NOT NULL,
	USER_ID_SUBMITTER BIGINT NOT NULL,
	USER_ID_HR_ADVISOR BIGINT,
	USER_ID_HIRING_MANAGER BIGINT,
	USER_ID_SUB_DELEGATED_MANAGER BIGINT,
	LANGUAGE_ID BIGINT,
	LANGUAGE_REQUIREMENT_ID BIGINT,
	EMPLOYMENT_TENURE_ID BIGINT,
	SELECTION_PROCESS_TYPE_ID BIGINT,
	APPOINTMENT_NON_ADVERTISED_ID BIGINT,
	WORK_SCHEDULE_ID BIGINT,
	NAME_EN NVARCHAR (200),
	NAME_FR NVARCHAR (200),
	LANGUAGE_PROFILE_EN NVARCHAR (3),
	LANGUAGE_PROFILE_FR NVARCHAR (3),
	SOMC_AND_CONDITION_EMPLOYMENT_EN NVARCHAR (MAX),
	SOMC_AND_CONDITION_EMPLOYMENT_FR NVARCHAR (MAX),
	PRIORITY_CLEARANCE_NUMBER NVARCHAR (20),
	PSC_CLEARANCE_NUMBER NVARCHAR(20),
	REQUEST_NUMBER NVARCHAR (10),
	POSITION_NUMBER NVARCHAR (100),
	SELECTION_PROCESS_NUMBER NVARCHAR (30),
	ALTERNATE_CONTACT_EMAIL_ADDRESS NVARCHAR (320),
	ADDITIONAL_COMMENT NVARCHAR (100),
	ALLOW_TELEWORK_IND BIT,
	EMPLOYMENT_EQUITY_NEED_IDENTIFIED_IND BIT,
	APPR_RCV_WMC_PMLC_IND BIT,
	APPT_RSLT_PRRT_ENTTLMNT_IND BIT,
	APPT_RSLT_PRRT_ENTTLMNT_RTNL NVARCHAR (200),
	HAS_PRVS_PRFRMD_DTS_IND BIT,
	START_DATE DATE,
	END_DATE DATE,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE REQUEST_CITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CITY_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE REQUEST_EMPLOYMENT_EQUITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	EMPLOYMENT_EQUITY_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);

CREATE TABLE [USER] 
(
	ID BIGINT NOT NULL IDENTITY, 
	USER_TYPE_ID BIGINT NOT NULL,
	LANGUAGE_ID BIGINT NOT NULL,
	MS_ENTRA_ID NVARCHAR (50) NOT NULL,
	FIRST_NAME NVARCHAR (100) NOT NULL,
	MIDDLE_NAME NVARCHAR (100),
	LAST_NAME NVARCHAR (100) NOT NULL,
	INITIAL NVARCHAR (4),
	PERSONAL_RECORD_IDENTIFIER NVARCHAR (10),
	BUSINESS_PHONE_NUMBER NVARCHAR (15),
	BUSINESS_EMAIL_ADDRESS NVARCHAR (320) NOT NULL,
	USER_CREATED NVARCHAR (50) NOT NULL,
	USER_UPDATED NVARCHAR (50)
);
