--liquibase formatted sql

--changeset system:1
CREATE TABLE CD_APPOINTMENT_NON_ADVERTISED 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (150) NOT NULL,
	NAME_FR VARCHAR (150) NOT NULL,
	INTERNAL_IND BIT NOT NULL DEFAULT 1,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_CITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	PROVINCE_TERRITORY_ID BIGINT NOT NULL,
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_CLASSIFICATION 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_EMPLOYMENT_EQUITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_EMPLOYMENT_OPPORTUNITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_EMPLOYMENT_TENURE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_LANGUAGE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_LANGUAGE_REFERRAL_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_LANGUAGE_REQUIREMENT 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_MATCH_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_PROFILE_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_PROVINCE_TERRITORY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_REQUEST_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_SECURITY_CLEARANCE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_SELECTION_PROCESS_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_USER_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_WFA_STATUS 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	SORT_ORDER INTEGER,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_WORK_SCHEDULE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CD_WORK_UNIT 
(
	ID BIGINT NOT NULL IDENTITY, 
	PARENT_WORK_UNIT_ID BIGINT,
	CODE VARCHAR (20) NOT NULL,
	NAME_EN VARCHAR (100) NOT NULL,
	NAME_FR VARCHAR (100) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE PROFILE_CITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	PROFILE_ID BIGINT NOT NULL,
	CITY_ID BIGINT NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE CLASSIFICATION_PROFILE 
(
	ID BIGINT NOT NULL IDENTITY, 
	CLASSIFICATION_ID BIGINT NOT NULL,
	PROFILE_ID BIGINT NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE EVENT 
(
	ID BIGINT NOT NULL IDENTITY, 
	TYPE VARCHAR (255) NOT NULL,
	DETAIL VARCHAR (4000),
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE MATCH 
(
	ID BIGINT NOT NULL IDENTITY, 
	PROFILE_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	MATCH_STATUS_ID BIGINT NOT NULL,
	HIRING_MANAGER_COMMENT VARCHAR (100),
	HR_ADVISOR_COMMENT VARCHAR (100),
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE PROFILE 
(
	ID BIGINT NOT NULL IDENTITY, 
	USER_ID BIGINT NOT NULL,
	USER_ID_HR_ADVISOR BIGINT,
	WFA_STATUS_ID BIGINT,
	CLASSIFICATION_ID BIGINT,
	CITY_ID BIGINT,
	WORK_UNIT_ID BIGINT,
	LANGUAGE_ID BIGINT,
	PROFILE_STATUS_ID BIGINT NOT NULL,
	PERSONAL_PHONE_NUMBER VARCHAR (15),
	PERSONAL_EMAIL_ADDRESS VARCHAR (320),
	PRIVACY_CONSENT_IND BIT DEFAULT 1,
	AVAILABLE_FOR_REFERRAL_IND BIT DEFAULT 1,
	INTERESTED_IN_ALTERNATION_IND BIT DEFAULT 1,
	ADDITIONAL_COMMENT VARCHAR (200),
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE PROFILE_EMPLOYMENT_OPPORTUNITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	EMPLOYMENT_OPPORTUNITY_ID BIGINT NOT NULL,
	PROFILE_ID BIGINT NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE PROFILE_LANGUAGE_REFERRAL_TYPE 
(
	ID BIGINT NOT NULL IDENTITY, 
	PROFILE_ID BIGINT NOT NULL,
	LANGUAGE_REFERRAL_TYPE_ID BIGINT NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE REQUEST 
(
	ID BIGINT NOT NULL IDENTITY,
	SECURITY_CLEARANCE_ID BIGINT,
	WORK_UNIT_ID BIGINT,
	CLASSIFICATION_ID BIGINT,
	REQUEST_STATUS_ID BIGINT NOT NULL,
	USER_ID_SUBMITTER BIGINT NOT NULL,
	USER_ID_HR_ADVISOR BIGINT,
	USER_ID_HIRING_MANAGER BIGINT,
	USER_ID_SUB_DELEGATED_MANAGER BIGINT,
	LANGUAGE_ID BIGINT,
	LANGUAGE_REQUIREMENT_ID BIGINT,
	EMPLOYMENT_TENURE_ID BIGINT,
	SELECTION_PROCESS_TYPE_ID BIGINT,
	APPOINTMENT_NON_ADVERTISED_ID BIGINT,
	WORK_SCHEDULE_ID BIGINT,
	NAME_EN VARCHAR (200),
	NAME_FR VARCHAR (200),
	LANGUAGE_PROFILE_EN VARCHAR (3),
	LANGUAGE_PROFILE_FR VARCHAR (3),
	SOMC_AND_CONDITION_EMPLOYMENT_EN VARCHAR (MAX),
	SOMC_AND_CONDITION_EMPLOYMENT_FR VARCHAR (MAX),
	PRIORITY_CLEARANCE_NUMBER VARCHAR (20),
	REQUEST_NUMBER VARCHAR (10),
	POSITION_NUMBER VARCHAR (100),
	SELECTION_PROCESS_NUMBER VARCHAR (30),
	ALTERNATE_CONTACT_EMAIL_ADDRESS VARCHAR (320),
	ADDITIONAL_COMMENT VARCHAR (100),
	ALLOW_TELEWORK_IND BIT,
	EMPLOYMENT_EQUITY_NEED_IDENTIFIED_IND BIT,
	APPR_RCV_WMC_PMLC_IND BIT,
	APPT_RSLT_PRRT_ENTTLMNT_IND BIT,
	APPT_RSLT_PRRT_ENTTLMNT_RTNL VARCHAR (200),
	HAS_PRVS_PRFRMD_DTS_IND BIT,
	START_DATE DATE,
	END_DATE DATE,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE REQUEST_CITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	CITY_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE REQUEST_EMPLOYMENT_EQUITY 
(
	ID BIGINT NOT NULL IDENTITY, 
	EMPLOYMENT_EQUITY_ID BIGINT NOT NULL,
	REQUEST_ID BIGINT NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);

CREATE TABLE [USER] 
(
	ID BIGINT NOT NULL IDENTITY, 
	USER_TYPE_ID BIGINT NOT NULL,
	LANGUAGE_ID BIGINT NOT NULL,
	MS_ENTRA_ID VARCHAR (50) NOT NULL,
	FIRST_NAME VARCHAR (100) NOT NULL,
	MIDDLE_NAME VARCHAR (100),
	LAST_NAME VARCHAR (100) NOT NULL,
	INITIAL VARCHAR (4),
	PERSONAL_RECORD_IDENTIFIER VARCHAR (10),
	BUSINESS_PHONE_NUMBER VARCHAR (15),
	BUSINESS_EMAIL_ADDRESS VARCHAR (320) NOT NULL,
	USER_CREATED VARCHAR (50) NOT NULL,
	USER_UPDATED VARCHAR (50)
);
