apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vacman-frontend
  labels:
    app.kubernetes.io/name: vacman-frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: AZUREAD_CLIENT_ID
      remoteRef: { key: shared, property: FRONTEND_AAD_CLIENT_ID }
    - secretKey: AZUREAD_CLIENT_SECRET
      remoteRef: { key: shared, property: FRONTEND_AAD_CLIENT_SECRET }
    - secretKey: DYNATRACE_API_KEY
      remoteRef: { key: shared, property: DYNATRACE_API_KEY }
    - secretKey: SESSION_COOKIE_SECRET
      remoteRef: { key: shared, property: SESSION_COOKIE_SECRET }
  target:
    template:
      data:
        AZUREAD_CLIENT_ID: '{{ .AZUREAD_CLIENT_ID }}'
        AZUREAD_CLIENT_SECRET: '{{ .AZUREAD_CLIENT_SECRET }}'
        OTEL_AUTH_HEADER: 'Api-Token {{ .DYNATRACE_API_KEY }}'
        SESSION_COOKIE_SECRET: '{{ .SESSION_COOKIE_SECRET }}'

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vacman-backend
  labels:
    app.kubernetes.io/name: vacman-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: AZUREAD_CLIENT_SECRET
      remoteRef: { key: shared, property: BACKEND_AAD_CLIENT_SECRET }
    - secretKey: DYNATRACE_API_KEY
      remoteRef: { key: shared, property: DYNATRACE_API_KEY }
    - secretKey: GCNOTIFY_API_KEY
      remoteRef: { key: shared, property: DYNATRACE_API_KEY }
    - secretKey: MSSQL_DB_NAME
      remoteRef: { key: shared, property: MSSQL_DB_NAME }
    - secretKey: MSSQL_HOST
      remoteRef: { key: shared, property: MSSQL_HOST }
    - secretKey: MSSQL_PASSWORD
      remoteRef: { key: shared, property: MSSQL_PASSWORD }
    - secretKey: MSSQL_USER
      remoteRef: { key: shared, property: MSSQL_USER }
  target:
    template:
      data:
        APPLICATION_GCNOTIFY_API_KEY: '{{ .GCNOTIFY_API_KEY }}'
        MANAGEMENT_OTLP_METRICS_EXPORT_HEADERS_AUTHORIZATION: 'Api-Token {{ .DYNATRACE_API_KEY }}'
        SPRING_DATASOURCE_URL: 'jdbc:sqlserver://{{ .MSSQL_HOST }};databaseName={{ .MSSQL_DB_NAME }};encrypt=true;trustServerCertificate=true;'
        SPRING_DATASOURCE_USERNAME: '{{ .MSSQL_USER }}'
        SPRING_DATASOURCE_PASSWORD: '{{ .MSSQL_PASSWORD }}'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MS-GRAPH_CLIENT_SECRET: '{{ .AZUREAD_CLIENT_SECRET }}'
