#######################################################################################################################
#
# Standard Spring Boot properties. Full reference available at:
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#
# This application supports configuration overrides using the following resolution order:
#
# 1. The usual Spring Boot configuration resolution:
#    https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
# 2. Config file src/dev/resources/application-local.yaml
#
# To set configuration properties that are local to your development environment
# (for example log levels or database connection strings), create the file
# src/dev/resources/application-local.yaml. This file is not managed by Git, so
# there is no chance of accidentally pushing your custom configuration to the
# project repository.
#
#######################################################################################################################

---

logging:
  level:
    '[ca.gov.dts_stn.vacman.api]': info

---

#######################################################################################################################
#
# Spring Boot properties
#
#######################################################################################################################

spring:
  application:
    name: vacman-api
  config:
    import:
      - optional:application-local.yml
      - optional:application-local.yaml
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;
    hikari: # see https://github.com/brettwooldridge/HikariCP#frequently-used
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  devtools:
    livereload:
      enabled: false
  flyway:
    sql-migration-prefix: v
    sql-migration-separator: '-'
    locations: classpath:db-migrations/common, classpath:db-migrations/{vendor}
  jackson:
    default-property-inclusion: non-null
    serialization:
      indent-output: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: ea3a6648-7e77-445b-b777-486d26367ee8
          authorities-claim-name: roles
          issuer-uri: https://login.microsoftonline.com/9ed55846-8a81-4246-acd8-b1a01abfc0d1/v2.0

---

#######################################################################################################################
#
# SpringDoc properties..
#
#######################################################################################################################

springdoc:
  pre-loading-enabled: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    oauth:
      client-id: ea3a6648-7e77-445b-b777-486d26367ee8
      scopes: ea3a6648-7e77-445b-b777-486d26367ee8/.default
      use-pkce-with-authorization-code-grant: true
  writer-with-default-pretty-printer: true
  writer-with-order-by-keys: true

---

#######################################################################################################################
#
# Application properties..
#
#######################################################################################################################

application:
  swagger-ui:
    application-name: Vacancy Manager API -- OpenAPI 3.0
    authentication:
      oauth:
        client-id: ea3a6648-7e77-445b-b777-486d26367ee8
        authorization-url: https://login.microsoftonline.com/9ed55846-8a81-4246-acd8-b1a01abfc0d1/oauth2/v2.0/authorize
        token-url: https://login.microsoftonline.com/9ed55846-8a81-4246-acd8-b1a01abfc0d1/oauth2/v2.0/token
    contact-name: Digital Technology Solutions
    contact-url: https://github.com/dts-stn/vacman/
    description: |
      This OpenAPI document describes the key areas where developers typically engage with the Vacancy Manager API.
    tos-url: https://www.canada.ca/en/transparency/terms.html
