# Example configuration demonstrating the new profile seeding capabilities
# This shows how to configure independent user and profile counts with flexible relationships

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=true;DB_CLOSE_DELAY=-1;
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

app:
  database:
    seeder:
      enabled: true
      clearDataFirst: true
      logSeedingProgress: true

      # Independent counts - users and profiles are now decoupled
      userCount: 50       # Total number of users to create
      profileCount: 75    # Total number of profiles to create
      requestCount: 30    # Total number of requests to create

      # User type distribution (must sum to 1.0)
      adminUserPercentage: 0.06     # 3 admin users (6% of 50)
      hiringManagerPercentage: 0.24 # 12 hiring managers (24% of 50)
      employeeUserPercentage: 0.70  # 35 employees (70% of 50)

      # Profile-to-user relationship configuration (must sum to 1.0)
      # This determines how profiles are distributed among users
      usersWithZeroProfilesPercentage: 0.16    # 8 users have no profiles (16% of 50 = ~8 users)
      usersWithOneProfilePercentage: 0.64      # 32 users have exactly one profile (64% of 50 = ~32 users)
      usersWithMultipleProfilesPercentage: 0.20 # 10 users have multiple profiles (20% of 50 = ~10 users)

      # Configuration for users with multiple profiles
      minProfilesPerUserWithMultiple: 2        # Each multi-profile user has at least 2 profiles
      maxProfilesPerUserWithMultiple: 5        # Each multi-profile user has at most 5 profiles
      ensureOneActiveProfilePerUser: true      # Each user with profiles has exactly one ACTIVE profile

      # Profile status distribution for profiles not constrained by above rule
      # These percentages apply to profiles that aren't forced to be ACTIVE
      activeProfilePercentage: 0.60   # 60% of remaining profiles are active
      inactiveProfilePercentage: 0.25 # 25% are inactive
      pendingProfilePercentage: 0.15  # 15% are pending

      # Expected outcome with above configuration:
      # - 8 users with 0 profiles = 0 profiles
      # - 32 users with 1 profile each = 32 profiles (with status distribution applied)
      # - 10 users with 2-5 profiles each = ~30-35 profiles (1 ACTIVE per user + others with status distribution)
      # - Additional standalone profiles to reach target of 75 total
      # - Each user with profiles will have exactly 1 ACTIVE profile (if ensureOneActiveProfilePerUser: true)

      # Other seeding configuration...
      useFixedSeed: true
      randomSeed: 12345
      validateRelationships: true
