-- Initialize provinces/territories
INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_ID], [PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (1, 'ON', 'Ontario', 'Ontario', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_ID], [PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (2, 'QC', 'Quebec', 'Québec', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_ID], [PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (3, 'BC', 'British Columbia', 'Colombie-Britannique', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_ID], [PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (4, 'AB', 'Alberta', 'Alberta', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize cities
-- Ontario cities
INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (1, 'TOR', 'Toronto', 'Toronto', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (2, 'OTT', 'Ottawa', 'Ottawa', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (3, 'HAM', 'Hamilton', 'Hamilton', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Quebec cities
INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (4, 'MTL', 'Montreal', 'Montréal', 2, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (5, 'QUE', 'Quebec City', 'Québec', 2, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (6, 'GAT', 'Gatineau', 'Gatineau', 2, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- British Columbia cities
INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (7, 'VAN', 'Vancouver', 'Vancouver', 3, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (8, 'VIC', 'Victoria', 'Victoria', 3, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Alberta cities
INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (9, 'CAL', 'Calgary', 'Calgary', 4, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_ID], [CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES (10, 'EDM', 'Edmonton', 'Edmonton', 4, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);