-- Initialize provinces/territories
INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('ON', 'Ontario', 'Ontario', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('QC', 'Quebec', 'Québec', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('BC', 'British Columbia', 'Colombie-Britannique', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AB', 'Alberta', 'Alberta', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('MB', 'Manitoba', 'Manitoba', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('NB', 'New Brunswick', 'Nouveau-Brunswick', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('NL', 'Newfoundland and Labrador', 'Terre-Neuve et Labrador', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('NT', 'Northwest Territories', 'Territoires du Nord-Ouest', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('NS', 'Nova Scotia', 'Nouvelle-Écosse', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('NU', 'Nunavut', 'Nunavut', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('PE', 'Prince Edward Island', 'Île-du-Prince-Édouard', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('SK', 'Saskatchewan', 'Saskatchewan', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_PROVINCE_TERRITORY] ([PROVINCE_TERRITORY_CODE], [PROVINCE_TERRITORY_NAME_EN], [PROVINCE_TERRITORY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('YT', 'Yukon', 'Yukon', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize cities
-- Ontario cities
INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('ON72', 'Toronto', 'Toronto', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'ON'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('ON52', 'Ottawa', 'Ottawa', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'ON'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('ON27', 'Hamilton', 'Hamilton', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'ON'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Quebec cities
INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('QC39', 'Montreal', 'Montréal', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'QC'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('QC42', 'Quebec City', 'Québec', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'QC'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('QC21', 'Gatineau', 'Gatineau', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'QC'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- British Columbia cities
INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('BC32', 'Vancouver', 'Vancouver', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'BC'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('BC35', 'Victoria', 'Victoria', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'BC'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Alberta cities
INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AB2', 'Calgary', 'Calgary', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'AB'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CITY] ([CITY_CODE], [CITY_NAME_EN], [CITY_NAME_FR], [PROVINCE_TERRITORY_ID], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AB4', 'Edmonton', 'Edmonton', (SELECT PROVINCE_TERRITORY_ID FROM CD_PROVINCE_TERRITORY WHERE PROVINCE_TERRITORY_CODE = 'AB'), CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize WFA statuses
INSERT INTO [CD_WFA_STATUS] ([WFA_STATUS_CODE], [WFA_STATUS_NAME_EN], [WFA_STATUS_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AFFECTED', 'Affected', 'Touché', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WFA_STATUS] ([WFA_STATUS_CODE], [WFA_STATUS_NAME_EN], [WFA_STATUS_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('SURPLUS_GRJO', 'Surplus with GRJO', 'Excédentaire avec GOE', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WFA_STATUS] ([WFA_STATUS_CODE], [WFA_STATUS_NAME_EN], [WFA_STATUS_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('SURPLUS_NO_GRJO', 'Surplus without a GRJO', 'Excédentaire sans GOE', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WFA_STATUS] ([WFA_STATUS_CODE], [WFA_STATUS_NAME_EN], [WFA_STATUS_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('RELOCATION', 'Relocation of work unit', 'Réinstallation de l''unité de travail', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WFA_STATUS] ([WFA_STATUS_CODE], [WFA_STATUS_NAME_EN], [WFA_STATUS_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LAYOFF', 'Lay-off', 'Mise à pied', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize classifications
INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AS-01', 'AS-01', 'AS-01', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AS-02', 'AS-02', 'AS-02', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AS-03', 'AS-03', 'AS-03', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AS-04', 'AS-04', 'AS-04', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AS-05', 'AS-05', 'AS-05', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AS-06', 'AS-06', 'AS-06', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('AS-07', 'AS-07', 'AS-07', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CR-03', 'CR-03', 'CR-03', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CR-04', 'CR-04', 'CR-04', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CR-05', 'CR-05', 'CR-05', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CT-FIN-01', 'CT-FIN-01', 'CT-FIN-01', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CT-FIN-02', 'CT-FIN-02', 'CT-FIN-02', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CT-FIN-03', 'CT-FIN-03', 'CT-FIN-03', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CT-FIN-04', 'CT-FIN-04', 'CT-FIN-04', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_CLASSIFICATION] ([CLASSIFICATION_CODE], [CLASSIFICATION_NAME_EN], [CLASSIFICATION_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('CT-IAU-01', 'CT-IAU-01', 'CT-IAU-01', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);





-- Initialize employment tenures
INSERT INTO [CD_EMPLOYMENT_TENURE] ([EMPLOYMENT_TENURE_CODE], [EMPLOYMENT_TENURE_NAME_EN], [EMPLOYMENT_TENURE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('INDETERMINATE', 'Indeterminate', 'Indéterminée', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('TERM', 'Term', 'Durée déterminée', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('CASUAL', 'Casual', 'Occasionnel', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('STUDENT', 'Student', 'Étudiant', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);



-- Initialize work units (parent entities)
INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-COPD', 'Labour - COPD', 'Travail - CODP', CURRENT_TIMESTAMP, NULL, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-SIG', 'Labour - SIG', 'Travail - ISG', CURRENT_TIMESTAMP, NULL, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR', 'DMO Labour Program', 'BSM Programme du travail', CURRENT_TIMESTAMP, NULL, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-PDRIA', 'Labour - PDRIA', 'Travail - PRDAI', CURRENT_TIMESTAMP, NULL, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('ICSD-QC', 'Integrated Client Service Delivery (ICSD) - Quebec Region', 'Prestation de services intégrés à la clientèle (PSIC) - PSIC, Région du Québec', CURRENT_TIMESTAMP, NULL, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize work units (child entities)
INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-COPD-1', 'Workplace Directorate', 'Direction du milieu de travail', CURRENT_TIMESTAMP, (SELECT WORK_UNIT_ID FROM CD_WORK_UNIT WHERE WORK_UNIT_CODE = 'LABOUR-COPD'), 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-COPD-2', 'ADM''s Office, COPD', 'Bureau du SMA, CODP', CURRENT_TIMESTAMP, (SELECT WORK_UNIT_ID FROM CD_WORK_UNIT WHERE WORK_UNIT_CODE = 'LABOUR-COPD'), 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-SIG-1', 'Strat Integ & Info Solutions', 'Integ Strat & Solution Info', CURRENT_TIMESTAMP, (SELECT WORK_UNIT_ID FROM CD_WORK_UNIT WHERE WORK_UNIT_CODE = 'LABOUR-SIG'), 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-1', 'DMO Labour Program - Unit 1', 'BSM Programme du travail - Unité 1', CURRENT_TIMESTAMP, (SELECT WORK_UNIT_ID FROM CD_WORK_UNIT WHERE WORK_UNIT_CODE = 'LABOUR'), 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('LABOUR-PDRIA-1', 'DGO Fed Mediatn Conciliatn Svc', 'DG Serv Fed Mediatn Conciliatn', CURRENT_TIMESTAMP, (SELECT WORK_UNIT_ID FROM CD_WORK_UNIT WHERE WORK_UNIT_CODE = 'LABOUR-PDRIA'), 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_WORK_UNIT] ([WORK_UNIT_CODE], [WORK_UNIT_NAME_EN], [WORK_UNIT_NAME_FR], [EFFECTIVE_DATE], [PARENT_WORK_UNIT_ID], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('ICSD-QC-1', 'Integrity Services Branch, QC', 'Direction serv d''intégrité, QC', CURRENT_TIMESTAMP, (SELECT WORK_UNIT_ID FROM CD_WORK_UNIT WHERE WORK_UNIT_CODE = 'ICSD-QC'), 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize languages
INSERT INTO [CD_LANGUAGE] ([LANGUAGE_CODE], [LANGUAGE_NAME_EN], [LANGUAGE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('EN', 'English', 'Anglais', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO [CD_LANGUAGE] ([LANGUAGE_CODE], [LANGUAGE_NAME_EN], [LANGUAGE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES ('FR', 'French', 'Français', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Add profile status values if not exists
INSERT INTO [CD_PROFILE_STATUS] ([PROFILE_STATUS_CODE], [PROFILE_STATUS_NAME_EN], [PROFILE_STATUS_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('PENDING', 'Pending', 'En attente', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ACTIVE', 'Active', 'Actif', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('INCOMPLETE', 'Incomplete', 'Incomplet', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ARCHIVED', 'Archived', 'Archivé', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Add priority levels if not exists
INSERT INTO [CD_PRIORITY_LEVEL] ([PRIORITY_LEVEL_CODE], [PRIORITY_LEVEL_NAME_EN], [PRIORITY_LEVEL_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('LOW', 'Low', 'Faible', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('NORMAL', 'Normal', 'Normal', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('HIGH', 'High', 'Élevé', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Add user types if not exists
INSERT INTO [CD_USER_TYPE] ([USER_TYPE_CODE], [USER_TYPE_NAME_EN], [USER_TYPE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('employee', 'Employee', 'Employé', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('admin', 'Administrator', 'Administrateur', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('hiring-manager', 'Hiring Manager', 'Gestionnaire de recrutement', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('hr-advisor', 'HR Advisor', 'Conseiller RH', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Add security clearance levels
INSERT INTO [CD_SECURITY_CLEARANCE] ([SECURITY_CLEARANCE_CODE], [SECURITY_CLEARANCE_NAME_EN], [SECURITY_CLEARANCE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('NONE', 'No Clearance Required', 'Aucune autorisation requise', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('RELIABILITY', 'Reliability', 'Fiabilité', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('SECRET', 'Secret', 'Secret', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('TOP_SECRET', 'Top Secret', 'Très secret', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Add request status values
INSERT INTO [CD_REQUEST_STATUS] ([REQUEST_STATUS_CODE], [REQUEST_STATUS_NAME_EN], [REQUEST_STATUS_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('DRAFT', 'Draft', 'Brouillon', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('SUBMITTED', 'Submitted', 'Soumis', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('UNDER_REVIEW', 'Under Review', 'En cours d''examen', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('APPROVED', 'Approved', 'Approuvé', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('REJECTED', 'Rejected', 'Rejeté', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('CANCELLED', 'Cancelled', 'Annulé', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize employment opportunities
INSERT INTO [CD_EMPLOYMENT_OPPORTUNITY] ([EMPLOYMENT_OPPORTUNITY_CODE], [EMPLOYMENT_OPPORTUNITY_NAME_EN], [EMPLOYMENT_OPPORTUNITY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('INTERNAL', 'Internal Opportunities', 'Opportunités internes', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('EXTERNAL', 'External Opportunities', 'Opportunités externes', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ADVERTISED', 'Advertised Processes', 'Processus annoncés', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('NON_ADVERTISED', 'Non-Advertised Processes', 'Processus non annoncés', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize language requirements (using DATE fields as per DDL)
INSERT INTO [CD_LANGUAGE_REQUIREMENT] ([LANGUAGE_REQUIREMENT_CODE], [LANGUAGE_REQUIREMENT_NAME_EN], [LANGUAGE_REQUIREMENT_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('BBB', 'BBB/BBB', 'BBB/BBB', CURRENT_TIMESTAMP, 'system', CAST(CURRENT_TIMESTAMP AS DATE), 'system', CAST(CURRENT_TIMESTAMP AS DATE)),
    ('CBC', 'CBC/CBC', 'CBC/CBC', CURRENT_TIMESTAMP, 'system', CAST(CURRENT_TIMESTAMP AS DATE), 'system', CAST(CURRENT_TIMESTAMP AS DATE)),
    ('CCC', 'CCC/CCC', 'CCC/CCC', CURRENT_TIMESTAMP, 'system', CAST(CURRENT_TIMESTAMP AS DATE), 'system', CAST(CURRENT_TIMESTAMP AS DATE)),
    ('ENG_ESSENTIAL', 'English Essential', 'Anglais essentiel', CURRENT_TIMESTAMP, 'system', CAST(CURRENT_TIMESTAMP AS DATE), 'system', CAST(CURRENT_TIMESTAMP AS DATE)),
    ('FRE_ESSENTIAL', 'French Essential', 'Français essentiel', CURRENT_TIMESTAMP, 'system', CAST(CURRENT_TIMESTAMP AS DATE), 'system', CAST(CURRENT_TIMESTAMP AS DATE)),
    ('BILINGUAL_ESSENTIAL', 'Bilingual Essential', 'Bilingue essentiel', CURRENT_TIMESTAMP, 'system', CAST(CURRENT_TIMESTAMP AS DATE), 'system', CAST(CURRENT_TIMESTAMP AS DATE));

-- Initialize selection process types
INSERT INTO [CD_SELECTION_PROCESS_TYPE] ([SELECTION_PROCESS_TYPE_CODE], [SELECTION_PROCESS_TYPE_NAME_EN], [SELECTION_PROCESS_TYPE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('COMPETITIVE', 'Competitive Process', 'Processus concurrentiel', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('NON_COMPETITIVE', 'Non-Competitive Process', 'Processus non concurrentiel', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('INVENTORY', 'Inventory Process', 'Processus d''inventaire', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('POOL', 'Pool Process', 'Processus de bassin', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize work schedule types
INSERT INTO [CD_WORK_SCHEDULE] ([WORK_SCHEDULE_CODE], [WORK_SCHEDULE_NAME_EN], [WORK_SCHEDULE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('FULL_TIME', 'Full-time', 'Temps plein', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('PART_TIME', 'Part-time', 'Temps partiel', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('CASUAL', 'Casual', 'Occasionnel', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('TERM', 'Term', 'Durée déterminée', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize employment equity
INSERT INTO [CD_EMPLOYMENT_EQUITY] ([EMPLOYMENT_EQUITY_CODE], [EMPLOYMENT_EQUITY_NAME_EN], [EMPLOYMENT_EQUITY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('VISIBLE_MINORITY', 'Visible Minority', 'Minorité visible', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ABORIGINAL', 'Aboriginal', 'Autochtone', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('WOMEN', 'Women', 'Femmes', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('PERSONS_WITH_DISABILITIES', 'Persons with Disabilities', 'Personnes handicapées', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize employment opportunities
INSERT INTO [CD_EMPLOYMENT_OPPORTUNITY] ([EMPLOYMENT_OPPORTUNITY_CODE], [EMPLOYMENT_OPPORTUNITY_NAME_EN], [EMPLOYMENT_OPPORTUNITY_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('DEPLOYMENT', 'Deployment', 'Mutation', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('PROMOTION', 'Promotion', 'Promotion', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('APPOINTMENT', 'Appointment', 'Nomination', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ACTING', 'Acting Assignment', 'Intérim', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('SECONDMENT', 'Secondment', 'Détachement', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize language referral types
INSERT INTO [CD_LANGUAGE_REFERRAL_TYPE] ([LANGUAGE_REFERRAL_TYPE_CODE], [LANGUAGE_REFERRAL_TYPE_NAME_EN], [LANGUAGE_REFERRAL_TYPE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('BILINGUAL', 'Bilingual', 'Bilingue', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ENGLISH', 'English only', 'Anglais seulement', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('FRENCH', 'French only', 'Français seulement', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize selection process types
INSERT INTO [CD_SELECTION_PROCESS_TYPE] ([SELECTION_PROCESS_TYPE_CODE], [SELECTION_PROCESS_TYPE_NAME_EN], [SELECTION_PROCESS_TYPE_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('INTERNAL', 'Internal Selection', 'Sélection interne', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('EXTERNAL', 'External Selection', 'Sélection externe', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('COMBINED', 'Combined Selection', 'Sélection combinée', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

-- Initialize appointment non-advertised types
INSERT INTO [CD_APPOINTMENT_NON_ADVERTISED] ([APPOINTMENT_NON_ADVERTISED_CODE], [APPOINTMENT_NON_ADVERTISED_NAME_EN], [APPOINTMENT_NON_ADVERTISED_NAME_FR], [EFFECTIVE_DATE], [USER_CREATED], [DATE_CREATED], [USER_UPDATED], [DATE_UPDATED])
VALUES
    ('NONE', 'Not Applicable', 'Sans objet', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('EXCEPTIONAL_CASE', 'Exceptional Case', 'Cas exceptionnel', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('URGENT_REQUIREMENT', 'Urgent Requirement', 'Besoin urgent', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('DEPLOYMENT', 'Deployment', 'Déploiement', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ASSIGNMENT', 'Assignment', 'Affectation', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('SECONDMENT', 'Secondment', 'Détachement', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('INTERCHANGE', 'Interchange', 'Échange', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
