#######################################################################################################################
# Configuration intended to be mounted as `application-local.yaml` for the vacman-backend Spring Boot application.
#
# This file provides environment-specific overrides to the default configuration.
#######################################################################################################################

logging:
  level:
    '[ca.gov.dts_stn.vacman.api]': trace

management:
  otlp:
    metrics:
      export:
        url: https://dynatrace.dev-dp.admin.dts-stn.com/e/21a07aef-852b-4d9b-aa87-ee5f8b79f8c9/api/v2/otlp/v1/metrics

spring:
  jpa:
    show-sql: true

application:
  gcnotify:
    base-url: https://api.notification.example.com/v2/notifications
    profile-approved-template-id: 00000000-0000-0000-0000-000000000000
    profile-created-template-id: 00000000-0000-0000-0000-000000000000
    profile-updated-template-id: 00000000-0000-0000-0000-000000000000
  security:
    # Disables custom application security.
    # ⚠️ MAKE SURE THIS IS NEVER SET TO TRUE IN PRODUCTION ⚠️
    disabled: true
