package ca.gov.dtsstn.vacman.api.web.model;

import java.time.Instant;
import java.time.LocalDate;
import java.util.Collection;

import io.soabase.recordbuilder.core.RecordBuilder;
import io.swagger.v3.oas.annotations.media.Schema;

@RecordBuilder
@Schema(name = "RequestRead")
public record RequestReadModel(

	@Schema(description = "Additional comments on this request.", example = "One cool request.")
	String additionalComment,

	@Schema(description = "Alternate contact email address.", example = "user@example.com")
	String alternateContactEmailAddress,

	@Schema(description = "Reason for the appointment from a non-advertised process of this request.")
	NonAdvertisedAppointmentReadModel appointmentNonAdvertised,

	@Schema(description = "City of this request.")
	Collection<CityReadModel> cities,

	@Schema(description = "Classification of this request.")
	ClassificationReadModel classification,

	@Schema(description = "List of Employment Equity identified of this request.")
	Collection<EmploymentEquityReadModel> employmentEquities,

	@Schema(description = "Employment Tenure")
	EmploymentTenureReadModel employmentTenure,

	@Schema(description = "English language profile of this request.")
	String englishLanguageProfile,

	@Schema(description = "English SOMC of this request.")
	String englishStatementOfMerit,

	@Schema(description = "English title of this request.", example = "Software Engineer")
	String englishTitle,

	@Schema(description = "Is Employment Equity required in this request.")
	Boolean equityNeeded,

	@Schema(description = "French language profile of this request.")
	String frenchLanguageProfile,

	@Schema(description = "French SOMC of this request.")
	String frenchStatementOfMerit,

	@Schema(description = "French title of this request.", example = "Ingénieur informatique")
	String frenchTitle,

	@Schema(description = "Whether or not this hiring request has employee profile matches.")
	Boolean hasMatches,

	@Schema(description = "Has the person proposed previously performed the same duties in the last twelve months or is this person still currently performing them in any capacity?")
	Boolean hasPerformedSameDuties,

	@Schema(description = "Hiring Manager user of this request.")
	UserReadModel hiringManager,

	@Schema(description = "HR Advisor that picked up this request.")
	UserReadModel hrAdvisor,

	@Schema(description = "Language of Correspondence for this request.")
	LanguageReadModel languageOfCorrespondence,

	@Schema(description = "Language requirement of this request.")
	LanguageRequirementReadModel languageRequirement,

	@Schema(description = "Position numbers of this request. Comma separated list of position numbers.", example = "12345, 67890")
	String positionNumber,

	@Schema(description = "The Clearance number generated by VacMan.", example = "???")
	String priorityClearanceNumber,

	@Schema(description = "Priority Entitlement of this request.")
	Boolean priorityEntitlement,

	@Schema(description = "Priority Entitlement Rationale of this request.")
	String priorityEntitlementRationale,

	@Schema(description = "Scheduled end date of this request.")
	LocalDate projectedEndDate,

	@Schema(description = "Scheduled start date of this request.")
	LocalDate projectedStartDate,

	@Schema(description = "The Clearance number received from PSC.", example = "???")
	String pscClearanceNumber,

	@Schema(description = "The request number.", example = "123-111")
	String requestNumber,

	@Schema(description = "Security clearance required of this request.")
	SecurityClearanceReadModel securityClearance,

	@Schema(description = "Selection Process Number of this request.", example = "12345")
	String selectionProcessNumber,

	@Schema(description = "Selection Process Type of this request.")
	SelectionProcessTypeReadModel selectionProcessType,

	@Schema(description = "Status of this request.")
	RequestStatusReadModel status,

	@Schema(description = "Sub Delegated user of this request.")
	UserReadModel subDelegatedManager,

	@Schema(description = "User that submitted of this request.")
	UserReadModel submitter,

	@Schema(description = "Is telework allowed for this request.")
	Boolean teleworkAllowed,

	@Schema(description = "Workforce Management Approved of this request.")
	Boolean workforceMgmtApprovalRecvd,

	@Schema(description = "Work Schedule of this request.")
	WorkScheduleReadModel workSchedule,

	@Schema(description = "Work Unit of this request.")
	WorkUnitReadModel workUnit,

	//
	// tombstone fields
	//

	@Schema(description = "The unique identifier for this profile.", example = "1")
	Long id,

	@Schema(description = "The user or service that created this request.", example = "vacman-api")
	String createdBy,

	@Schema(description = "The time this request was created.", example = "2000-01-01T00:00:00Z")
	Instant createdDate,

	@Schema(description = "The request or service that last modified this request.", example = "vacman-api")
	String lastModifiedBy,

	@Schema(description = "The time this request was last modified.", example = "2000-01-01T00:00:00Z")
	Instant lastModifiedDate

) {}